### ISSUE TITLE
Connection Timeout when using proxy

### ISSUE THREAD

**Issue by andreihava-okta** [oktadeveloper/okta-aws-cli-assume-role#105]
Issue brought up via our [Dev Forums](https://devforum.okta.com/t/awscli-connection-timeout/1483)

**Issue:** While using Amazon's CLI tool after setting the HTTP_PROXY parameter, connection is successful. However, using Okta's AWS CLI tool after setting the HTTP_PROXY parameter results in a connection timeout.

**Amazon's Tool:**
```
.okta>set HTTPS_PROXY=https://<<PROXY.URL>>
.okta>aws iam get-user
{
    “User”: {
        “UserName”: “XXXX”,
        “PasswordLastUsed”: “",
        “CreateDate”: "",
        “UserId”: "*********",
        “Path”: “/”,
        “Arn”: "arn:aws:iam::*********:user/”
    }
}
```

**Okta's Tool:**
```
.okta>java -classpath ".okta\*" com.okta.tools.awscli
Username: *************
Password:

Exception in thread "main" **org.apache.http.conn.ConnectTimeoutException: Connect to XXXXX.oktapreview.com:443**
[XXXXX.oktapreview.com/999.999.226.139, XXXXX.oktapreview.com/999.999.81.89, XXXXX.oktapreview.com/999.999.80.210,
 XXXXX.oktapreview.com/999.999.76.2, XXXXX.oktapreview.com/000.999.80.174, XXXXX.oktapreview.com/999.999.226.145]
failed: Read timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOp
erator.java:150)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionMan
ager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.okta.tools.OktaAwsCliAssumeRole.logInToOkta(OktaAwsCliAssumeRole.java:271)
        at com.okta.tools.OktaAwsCliAssumeRole.getAuthnResponse(OktaAwsCliAssumeRole.java:208)
        at com.okta.tools.OktaAwsCliAssumeRole.getOktaSessionToken(OktaAwsCliAssumeRole.java:178)
        at com.okta.tools.OktaAwsCliAssumeRole.getSamlResponse(OktaAwsCliAssumeRole.java:124)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:111)
        at com.okta.tools.awscli.main(awscli.java:31)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket
```

**Wireshark Trace:**
![okta_packet](https://user-images.githubusercontent.com/36082423/37818003-9529ba6c-2e70-11e8-987d-20eebf5e3b40.png)

CC: @AlainODea @mraible

**Comment by AlainODea** [comment]
This is easy to fix. They need to set the proxy for Java.

The proxy for Java can be set globally as described here:
https://java.com/en/download/help/proxy_setup.xml

Proxies can be set per-process as described here:
https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

My PowerShell script pulls the Internet Options proxy settings on Windows:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/85#comment-375064040

**Comment by AlainODea** [comment]
Arguably, **withokta** and **awscli** could have `-Djava.net.useSystemProxies=true` in the JVM args. That should do the right thing in most cases.

The enviroment or config Java pulls the system proxy settings from with that setting enabled is undocumented, so YMMV.

It might be better to explicitly detect proxy environment and use it. It does open a can of worms with respect to APIs accessed through AWS PrivateLink:
https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpce-interface.html

I definitely have that challenge in my deployment and it requires configuring noProxyHosts carefully.

To be honest, this might be better left to site configuration by users until and unless we can provide very clear documentation of how we interpret different sources of proxy configuration and can confidently handle the no proxy hosts.

**Comment by AlainODea** [comment]
My fix for #88 includes proxy configuration based on Internet Options on Windows and http_proxy https_proxy environment on macOS/Linux.

**Comment by AlainODea** [comment]
That fix is #146.

**Comment by naiduklr936** [comment]
Sorry for the lack of clarity, I tried to add the proxy configuration on java control panel. But still the application is not able to fetch the proxy configuration from it. Do we have to tweak any changes for the code ?

**Comment by AlainODea** [comment]
No code changes are required. Proxy support is built into the libraries it uses. System proxies work on macOS, Ubuntu, and Windows in my tests.

On macOS and Ubuntu, it will use the https_proxy environment variable if installed using install.sh.

On Windows, the PowerShell installer sets it up to use the Internet Options proxy.

**Comment by naiduklr936** [comment]
Do I've to execute the power shell installer separately ?  where I can find the install.sh and power shell installer ? @AlainODea

**Comment by AlainODea** [comment]
Try this step-by-step installation guide:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/Readme.MD

If that doesn’t work, please let me know.

**Comment by naiduklr936** [comment]
@AlainODea After upgrading the PowerShell to version 5, I ran the following command 

`Invoke-RestMethod https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/Install-OktaAwsCli.ps1 | clip.exe`

But still, no luck passing through the proxy, still getting the same error.

**Comment by AlainODea** [comment]
@naiduklr936 after running that you need to right-click to run the installation. It puts the installer in your clipboard.

After that, within PowerShell running a command like `aws profilename s3 ls` should list your S3 buckets if the role you assume allows that.

Can you share the error you are getting (full stacktrace)?
