### ISSUE TITLE
aws cli reassign the tocken

### ISSUE THREAD

**Issue by DasChebattina** [oktadeveloper/okta-aws-cli-assume-role#113]
Hello,
I am able to setup 'okta-aws-cli-assume-role' tool successfully. 
Ran  'awscli sts get-caller-identity' command followed by aws cli commands (ex: aws s3 ls) with the  --profile <profile created by the tool>
Once the token expired after 1hr,  get this error when I ran aws s3 ls --profile <profile name>.
_An error occurred (ExpiredToken) when calling the ListBuckets operation: The provided token has expired_
So, ran command 'awscli sts get-caller-identity'. but getting the following error. 
Exception in thread "main" java.lang.IllegalStateException: Duplicate key DI07VqOgutdRFOEJZ0eHdgEEg
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.okta.tools.saml.OktaSaml.launchOktaAwsApp(OktaSaml.java:97)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:60)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:46)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)

Is there anything missing with the configuration or the commands?

**Comment by AlainODea** [comment]
This tool generates and stores AWS profiles in the standard AWS config and AWS credentials files. It can’t update them unless you run it explicitly.

You’ll need to periodically call through this tool to keep the AWS profile session from expiring.

I recommend using named profiles via the OKTA_PROFILE environment variable or config property. The tool will maintain the named profile and refresh it as needed if you make your calls through it or periodically call it.

**Comment by JLambeth** [comment]
I don't believe that this addresses the issue. I am facing a similar problem:

When I run `awscli sts get-caller-identity` once, I am asked to enter my credentials, choose a role, etc. The command completes successfully. If I execute the command again _immediately_ after seeing it complete successfully, I get the error:

`Exception in thread "main" java.lang.IllegalStateException: Duplicate key ...
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.okta.tools.helpers.CookieHelper.storeCookies(CookieHelper.java:66)
	at com.okta.tools.saml.OktaSaml.launchOktaAwsApp(OktaSaml.java:86)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:59)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:36)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)`

This is resolved by deleting the **cookies.properties** file, and re-running the command, _but_ I'm re-prompted for credentials even though my Okta configuration should only require these every 60 minutes.

**Comment by AlainODea** [comment]
**cookies.properties** is your Okta session effectively. Without that the 60 minute timeout can’t be determined because the tool sees you as having no session.

What does cookies.properties contain for you? Describe or mask the values as they are true authentication material.

It should be like this:

```
sid=some text (very sensitive do not share)
JSESSIONID=also sensitive
```

The names before the equals signs are not sensitive.

**Comment by JLambeth** [comment]
The **cookies.properties** file contains these values:

> #
> #Thu Jun 28 07:03:01 AEST 2018
> sid=**masked**
> proximity_**masked**=**masked**
> t=default
> DT=**masked**
> JSESSIONID=**masked**

The Duplicate key error is caused by the value of DT in the cookies file.

**Comment by AlainODea** [comment]
Interesting. I wonder why DT causes that. I have a DT entry as well.

It looks like there are multiple versions of the same cookie in the CookieStore.

There's a way to ignore this by providing a merge function to ignore duplicate keys here:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/src/main/java/com/okta/tools/helpers/CookieHelper.java#L66

Here's the fixed line:

```java
cookieStore.getCookies().stream().collect(Collectors.toMap(Cookie::getName, Cookie::getValue, (x, y) -> y))
```

I suspect that the CookieStore has cookies for multiple domains and they happen to overlap.

Are you comfortable writing and testing Java? We don't experience this issue and I don't have time to tackle it right now.

**Comment by felimartina** [comment]
I just started using this project and I'm facing the very same issue. Unfortunately, I don't have any java experience to be able to file a PR :/

**Comment by felimartina** [comment]
Thanks a lot @AlainODea...this bug was really preventing me from using the CLI at the time.
I will get back to it and take a look. I am sorry I couldn't be of much more help and contribute...so double thanks and kudos to you!

**Comment by AlainODea** [comment]
@felimartina my pleasure. I'm glad it helped you get up and running 😄
