### ISSUE TITLE
WithOkta throws an Exception

### ISSUE THREAD

**Issue by jimsmith** [oktadeveloper/okta-aws-cli-assume-role#117]
```
Version 1.0.2
OS: Windows 10 64bit
Java version: 1.8.0_162
```

**Issue**: After using WithOkta and getting Duo Push (built-in web browser gui opens) I authenticate and then get list of aws roles for assuming, I select the one I have access to and gives following error:
```
c:\temp\okta>java -Djava.awt.headless=true -Dprism.verbose=true -classpath c:\temp\okta\okta-aws-cli-1.0.2.jar com.okta.tools.WithOkta %
Prism pipeline init order: d3d sw
Using native-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.d3d.D3DPipeline
Loading D3D native library ...
        succeeded.
D3DPipelineManager: Created D3D9Ex device
Direct3D initialization succeeded
(X) Got class = class com.sun.prism.d3d.D3DPipeline
Initialized prism pipeline: com.sun.prism.d3d.D3DPipeline
Maximum supported texture size: 8192
Maximum texture size clamped to 4096
OS Information:
        Windows version 10.0 build 16299
D3D Driver Information:
        Intel(R) HD Graphics 520
        \\.\DISPLAY1
        Driver igdumdim64.dll, version 21.20.16.4550
        Pixel Shader version 3.0
        Device : ven_8086, dev_1916, subsys_505317AA
        Max Multisamples supported: 4
 vsync: true vpipe: true
Loading Prism common native library ...
        succeeded.
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_4
QuantumRenderer: shutdown

Please choose the role you would like to assume:
Account: REDACTED
        [ 1 ]: AdministratorAccess-CrossAccountRole
Account: REDACTED
        [ 2 ]: AdministratorAccess-CrossAccountRole
Account: REDACTED
        [ 3 ]: AdministratorAccess-CrossAccountRole
Account: REDACTED
        [ 4 ]: AdministratorAccess-CrossAccountRole
Account: REDACTED
        [ 5 ]: AdministratorAccess-CrossAccountRole
Account: REDACTED
        [ 6 ]: AdministratorAccess-CrossAccountRole

Selection: 6
Exception in thread "main" com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The requested DurationSeconds exceeds the MaxSessionDuration set for this role. (Service: AWSSecurityTokenService; Status Code: 400; Error Code: ValidationError; Request ID: a6a5f4ca-4ed3-11e8-82a1-85cac2dfc70b)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1278)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1254)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithSAML(AWSSecurityTokenServiceClient.java:610)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithSAML(AWSSecurityTokenServiceClient.java:585)
        at com.okta.tools.helpers.RoleHelper.assumeChosenAwsRole(RoleHelper.java:39)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:91)
        at com.okta.tools.WithOkta.main(WithOkta.java:23)
```

config.properties
```
OKTA_ORG=REDACTED.okta.com
OKTA_AWS_APP_URL=https://REDACTED.okta.com/home/amazon_aws/REDACTED/REDACTED
OKTA_USERNAME=
OKTA_PASSWORD=
OKTA_AWS_ROLE_TO_ASSUME=
OKTA_PROFILE=
OKTA_STS_DURATION=43200
OKTA_BROWSER_AUTH=true
```

**Comment by jimsmith** [comment]
Aligned OKTA_STS_DURATION to STS session timeout at AWS side.
