### ISSUE TITLE
Integrated web browser authentication doesn't work reliably

### ISSUE THREAD

**Issue by hao-public** [oktadeveloper/okta-aws-cli-assume-role#120]
When I use the OKTA_BROWSER_AUTH=true property in the config.properties file it will very often just sign me into AWS, after I select a Role. It doesn't return to the commandline where I executed the jar-file. It doesn't store a session token for me. If I repeat it many times, it will suddenly work - but only rarely.

**Comment by davidsuehring** [comment]
This is the behavior I'm seeing as well. The Java browser shows up, I'm prompted to authenticate and enter my Google Authenticator MFA token, and then am presented the list of roles in the Java browser, rather than on the command line.

**Comment by AlainODea** [comment]
That's very strange. This has been rock solid for the dozens of cloud ops and devs we have using it. I suspect it's a network environmental issue or a different AWS configuration I hadn't anticipated.

Here's the code responsible for guessing that the AWS SAML signin page has been reached successfully after SAML authentication:

https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/c9909aa71338209b5eb9141ca4217acfb10452b7/src/main/java/com/okta/tools/authentication/BrowserAuthentication.java#L94-L107

It looks for a **form** element with an **action** of **https://signin.aws.amazon.com/saml**. A decrypting/rewriting web proxy could alter the URLs and break the heuristic there. Do your AWS SAML signins go to https://signin.aws.amazon.com/saml?

If this is AWS China or GovCloud it's quite possible that there is a different endpoint I didn't design for, because we use neither of those.

**Comment by ghnboy** [comment]
I'm encountering the same issue here. It worked for me 2, 3 times only
It prompted to authenticate and enter my Okta Authenticator MFA token, and then am presented the list of roles in the Java browser, rather than on the command line.

I'm also seeing a java error while Java browser opened
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.okta.tools.authentication.BrowserAuthentication.getAwsStsSamlForm(BrowserAuthentication.java:95)
        at com.okta.tools.authentication.BrowserAuthentication.getSamlResponseForAws(BrowserAuthentication.java:89)
        at com.okta.tools.authentication.BrowserAuthentication.checkForAwsSamlSignon(BrowserAuthentication.java:82)
        at com.okta.tools.authentication.BrowserAuthentication.lambda$start$0(BrowserAuthentication.java:69)
        at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
        at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1287)
        at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1401)
        at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1280)
        at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1267)
        at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2518)
        at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2362)
        at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
        at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:871)
        at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$105(URLLoader.java:862)
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
        at java.lang.Thread.run(Unknown Source)

**Comment by AlainODea** [comment]
Fixed by #130 but not yet released. A release with this fix in it should be coming soon.

**Comment by AlainODea** [comment]
Fixed in release 1.0.3.
