### ISSUE TITLE
Sometimes OSX users get an empty list of roles

### ISSUE THREAD

**Issue by GavrielNsof** [oktadeveloper/okta-aws-cli-assume-role#138]
When running "awscli sts get-caller-identity", sometimes OSX users get no roles to choose,
Example:
```
$ awscli sts get-caller-identity

Please choose the role you would like to assume:
Selection:
```

After running the command a couple of times (random number) the list will appear.
Is this a known issue and is there a fix?

**Comment by sbrandtb** [comment]
This is not an issue with OSX. It happens for us in Docker containers as well. We debugged and tracked it down to AWS sending broken HTML. You know the page when you login to AWS using Okta where you can select your roles from multiple accounts? That's the one it's parsing and it seems like currently AWS is sending different versions - one broken and one non-broken, depending on the backend server you reach probably. See attached files.

* [awssignin-success.html.txt](https://github.com/oktadeveloper/okta-aws-cli-assume-role/files/2205793/awssignin-success.html.txt)
* [awssignin-broken.html.txt](https://github.com/oktadeveloper/okta-aws-cli-assume-role/files/2205794/awssignin-broken.html.txt)

Notice the stray `</head>` in the broken file. The HTML parser (jsoup) then fails to parse the file properly.

Furthermore, it came to our attention that it would not be required to make the request to AWS using th SAML response from Okta because the SAML response already contains the information in XML - So this tool is using AWS just as a parser/renderer. However, this still requires parsing HTML from Okta, which is still less than perfect, but a possible point of failure less.

We're working on a solution that uses the SAML response directly from Okta

**Comment by GavrielNsof** [comment]
Thanks for the quick answer, will love to know once this is resolved.
Just another quick question: are you sure it's not related to OSX? 3 of our OSX users experienced this while the other 10 ubuntu users did not

**Comment by sbrandtb** [comment]
@GavrielNsof I'm not 100% sure why it only seems to happen on OSX. We're two developers here trying out the Okta-AWS integration. One with Ubuntu, one with OSX. In fact, it does not happen on Ubuntu, but on OSX *even* in a Docker container, which should be Linux.

So our best guess is that Ubuntu somehow receives only the correct answer and that the underlying issue even propagates into the Docker container on OSX. We think about DNS caching. Frankly, our explanation does not convince ourselves either.

Also, I think I know now why this project is parsing AWS' response and is not unly using the SAML response: The latter does not include the human readable name of an account. Just the number.

**Comment by GavrielNsof** [comment]
Not sure if it helps but other SAML tools don't have this problem on OSX, (saml2aws for example)
(they do lack other features though).

**Comment by sbrandtb** [comment]
@GavrielNsof I think that's because all tools I've checked so far are not using the page rendered by AWS

**Comment by sbrandtb** [comment]
So, we analyzed this one further and came to conclusion that it's actually an issue with the jsoup library. I will create a merge request within the our

**Comment by GavrielNsof** [comment]
Thanks @sbrandtb!

**Comment by GavrielNsof** [comment]
@sbrandtb if I may ask, how did you update Jsoup? did you just download the jar (what path)?
Also, will this be fixed in the next okta-aws-cli version?

Thanks!

**Comment by richievos** [comment]
Could we get a new release with this fix?

**Comment by mraible** [comment]
I’ll try to do one this week, but I’m traveling in Greece, so might be tough. In the meantime, you should be able to clone the project and run “mvn package” to create your own copy with this fix.

**Comment by nj80750** [comment]
Hi ..

Created the JAR file but it is giving a different error now. Although the issue with the empty list of roles seems to be fixed.

Attached is the error..


Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1533)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:157)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:403)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:352)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461)
	at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:3838)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3732)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2796)
	at com.amazonaws.partitions.PartitionsLoader.loadPartitionFromStream(PartitionsLoader.java:92)
	at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:84)
	at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
	at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
	at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
	at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
	at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:239)
	at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:226)
	at com.okta.tools.helpers.RoleHelper.assumeChosenAwsRole(RoleHelper.java:36)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:109)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
	at com.okta.tools.awscli.main(awscli.java:28)

>

**Comment by sbrandtb** [comment]
@nj80750 looks like you used the jarfile from my fork where I tried to reduce the jarfile's size by removing lots of unused AWS stuff. Unfortunately, this leads to the error you posted.

Please compile the jar file on your own or use [my updated one](https://github.com/FRI-DAY/okta-aws-cli-assume-role/releases/tag/v1.0.3-friday3).

**Comment by AlainODea** [comment]
This is an amazing exchange. Thank you @sbrandtb! This is a huge contribution and awesome analysis work.

**Comment by gtaman** [comment]
I too am having this issue with the automated install jar.  1.0.3

**Comment by AlainODea** [comment]
@gtaman. The install is still using 1.0.2. I’ll fix that. Have you downloaded the 1.0.3 release manually?
