### ISSUE TITLE
No selections listed

### ISSUE THREAD

**Issue by mfuery** [oktadeveloper/okta-aws-cli-assume-role#149]
```
$ awscli

Please choose the role you would like to assume:
Selection:
```

I should be seeing 6 options.  This happens often, but not always.  Using v.1.0.2.

OKTA_ORG=benefitcosmetics.okta.com
OKTA_AWS_APP_URL=https://benefitcosmetics.okta.com/home/amazon_aws/0oa8ftulnWoma7AHY2p6/272
OKTA_USERNAME=michaelf@benefitcosmetics.com
OKTA_PASSWORD=XXXXXX

**Comment by mfuery** [comment]
Often times out
```$ aws test sts get-caller-identity
Exception in thread "main" com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The requested DurationSeconds exceeds the MaxSessionDuration set for this role. (Service: AWSSecurityTokenService; Status Code: 400; Error Code: ValidationError; Request ID: 05648217-910f-11e8-961d-0314ab2fff5f)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1278)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1254)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithSAML(AWSSecurityTokenServiceClient.java:610)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithSAML(AWSSecurityTokenServiceClient.java:585)
	at com.okta.tools.helpers.RoleHelper.assumeChosenAwsRole(RoleHelper.java:39)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:91)
	at com.okta.tools.awscli.main(awscli.java:33)```

**Comment by AlainODea** [comment]
I've had a few reports of this, but I haven't been able to reproduce it.

I don't know what causes it. It's like the Okta session ends up in a bad state and can't generate the SAMLResponse for AWS properly.

The short term fix is running awscli logout and trying again.

If I had a reliable reproduction of the bug, I could develop a fix for it.

**Comment by mfuery** [comment]
I can repro it on my Macbook. What log(s) can I post here for you?

**Comment by AlainODea** [comment]
Thank you, @mfuery. I really appreciate it. There's no sensible logging regrettably. There is JDB...

I suspect that SAMLResponse is either:
1. not being parsed correctly from the form Okta builds to POST to `https://signin.aws.amazon.com/saml` (bug in this tool)
2. is parsed correctly, but occasionally contains no roles (Okta service-side admin misconfiguration, weird group rules issue, or bug)

I have to be very careful what I ask you to share since this handles extremely sensitive credential material internally.

Replace **java** with **jdb** in bin/awscli or bin/withokta. (to reverse this debug setup, just switch it back from jdb to java)

Run your test that reproduces the issue and you'll see this:

```plain
Initializing jdb ...
> 
```

At that prompt type this and hit enter:

```plain
stop on com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume
```

It will respond with this:

```plain
Deferring breakpoint com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume.
It will be set after the class is loaded.
> 
```

At that prompt type this and hit enter:

```plain
run
```

It will respond with this:

```plain
run com.okta.tools.WithOkta aws --profile default sts get-caller-identity
Set uncaught java.lang.Throwable
Set deferred uncaught java.lang.Throwable
>
VM Started: Set deferred breakpoint com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume

Breakpoint hit: "thread=main", com.okta.tools.helpers.RoleHelper.chooseAwsRoleToAssume(), line=43 bci=0

main[1] 
```

At that prompt type this and hit enter:

```plain
locals
```

It will respond with this:

```
Method arguments:
samlResponse = "huge block of HIGHLY SENSITIVE Base 64"
Local variables:
main[1]
```

IMPORTANT: **DO NOT** use online SAML decoders. They can expose your authenticated session to third-parties and compromise your security.

Save this URL-encoded Base 64-decoder decoder HTML locally and open it in your browser:
https://gist.github.com/AlainODea/9fd46ef07e254283f0277c1bdb827dd8

Copy the block of base 64 text (without the opening and closing double-quotes) and paste it into the top text area of that decoder page.

Click **Decode**.

The bottom text area will populate with the decoded XML of the SAMLResponse. It won't be nicely formatted (lots of optional white space will be removed).

You should see a series of entries like this:

```xml
<saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
    arn:aws:iam::123456789012:saml-provider/acmecorp.okta.com,arn:aws:iam::123456789012:role/EC2Admins
</saml2:AttributeValue>
<saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
    arn:aws:iam::210987654321:saml-provider/acmecorp.okta.com,arn:aws:iam::210987654321:role/S3Readers
</saml2:AttributeValue>
```

If you share aspects of the SAMLResponse you decode, please sanitize it first:
1. change arn:aws:iam:: values to mask your account numbers and IAM Role names
2. remove body of Issuer, DigestValue, SignatureValue, and X509Certificate elements
3. remove body of any NameID and Attribute elements containing private info

Here's an example (I've used acmecorp in place of my real org, used made-up account numbers and role name, and replaced the Issuer, DigestValue, SignatureValue, NameID, and Attribute element bodies with `<!-- REMOVED -->`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://signin.aws.amazon.com/saml"
                 ID="id144063247110259441538483103" IssueInstant="2018-08-01T18:39:55.864Z" Version="2.0"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"><!-- REMOVED -->
    </saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#id144063247110259441538483103">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                        <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"/>
                    </ds:Transform>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue><!-- REMOVED --></ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
            <!-- REMOVED -->
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate><!-- REMOVED -->
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:Status xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
        <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </saml2p:Status>
    <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="id144063247111887811958259393"
                     IssueInstant="2018-08-01T18:39:55.864Z" Version="2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                      xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><!-- REMOVED -->
        </saml2:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
                <ds:Reference URI="#id144063247111887811958259393">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                            <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"/>
                        </ds:Transform>
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                    <ds:DigestValue><!-- REMOVED -->=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>
                <!-- REMOVED -->
            </ds:SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate><!-- REMOVED -->
                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml2:Subject xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            <saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified"><!-- REMOVED -->
            </saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml2:SubjectConfirmationData NotOnOrAfter="2018-08-01T18:44:55.865Z"
                                               Recipient="https://signin.aws.amazon.com/saml"/>
            </saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions NotBefore="2018-08-01T18:34:55.865Z" NotOnOrAfter="2018-08-01T18:44:55.865Z"
                          xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            <saml2:AudienceRestriction>
                <saml2:Audience>urn:amazon:webservices</saml2:Audience>
            </saml2:AudienceRestriction>
        </saml2:Conditions>
        <saml2:AuthnStatement AuthnInstant="2018-08-01T18:39:55.864Z" SessionIndex="id1533148795864.1813133068"
                              xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
                </saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
            <saml2:Attribute Name="https://aws.amazon.com/SAML/Attributes/Role"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
                    arn:aws:iam::123456789012:saml-provider/acmecorp.okta.com,arn:aws:iam::123456789012:role/EC2Admins
                </saml2:AttributeValue>
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
                    arn:aws:iam::210987654321:saml-provider/acmecorp.okta.com,arn:aws:iam::210987654321:role/S3Readers
                </saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="https://aws.amazon.com/SAML/Attributes/RoleSessionName"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
                    <!-- REMOVED -->
                </saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="https://aws.amazon.com/SAML/Attributes/SessionDuration"
                             NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml2:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema"
                                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">14400
                </saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>
```

**Comment by mfuery** [comment]
@davidsuehring Indeed, it sure looks like it. I downloaded the 1.0.3 jar and will use that and see if it solves my issue. Thanks for linking me!!
