### ISSUE TITLE
Not able to use proxy when running Okta CLI from the Corporate Network

### ISSUE THREAD

**Issue by naiduklr936** [oktadeveloper/okta-aws-cli-assume-role#209]
https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases

jar file is downloaded from the above link. Using for the AWS cli, working fine if we are not in our corporate network, but when we are trying to work Okta CLI from the corporate network it's not going over proxy. Getting connection time out since it's hitting the firewalls directly

**Comment by AlainODea** [comment]
This is configurable via JVM Proxy settings.

This is a duplicate, so I’m going to close it. See notes on the original issue:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/105

**Comment by AlainODea** [comment]
@naiduklr936 I admit this is not very user friendly. In some cases the useSystemProxies works.

The Windows PowerShell integration with proxies is actually the best as we needed it to be solid for use in Amazon WorkSpaces.

**Comment by AlainODea** [comment]
I think this might be #214 so legitimate issue. I'll let you know when that gets merged. I imagine you are using a SOCKS proxy. You can build #217 if you need the fix urgently.

**Comment by naiduklr936** [comment]
Thanks, @AlainODea , I'll have a look. Also, recently we came across one more issue when one of our developer trying to use the Okta CLI for AWS from Ec2 Linux instance. He is able to generate the credentials, but when he executing the aws CLI commands it gives the access denied. I'm sure that he has required permissions for the role he generated the credentials. But still, he is not able to use them, seems like it assumes a different role than the one to be used.

**Comment by naiduklr936** [comment]
@AlainODea , I use the newer release 1.0.4, this is what I'm getting

$ java -jar okta-aws-cli-1.0.4.jar

Exception in thread "main" org.apache.http.conn.HttpHostConnectException: Connect to okta.com:443 [okta.com/xx.xx.xx.xx, okta.com/xx.xx.xx.xx, okta.com/xx.xx.xx.xx] failed: Connection timed out: connect
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.okta.tools.authentication.OktaAuthentication.primaryAuthentication(OktaAuthentication.java:154)
        at com.okta.tools.authentication.OktaAuthentication.getPrimaryAuthResponse(OktaAuthentication.java:115)
        at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:39)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:46)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:120)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
        at com.okta.tools.awscli.main(awscli.java:41)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        ... 16 more


Currently, we are facing these two issues.

**Comment by AlainODea** [comment]
Proxy settings are not automatically detected. You have to explicitly ask Java to detect your proxy or you need to configure it manually.

If you install this according to [our install guide](https://github.com/oktadeveloper/okta-aws-cli-assume-role#installation) it should work on Windows systems with proxies assuming standard configuration. I haven't tested proxy auto-detection on macOS or Linux.

On recent Windows and Gnome 2.x or later systems, Java may be able to detect your proxy settings automatically if you run this:
```
java -Djava.net.useSystemProxies=true -jar okta-aws-cli-1.0.4.jar
```

If your proxy is a SOCKS proxy on proxy.example.com port 1080, you can run this:
```
java -DsocksProxyHost=proxy.example.com -DsocksProxyPort=1080 -jar okta-aws-cli-1.0.4.jar
```

If your proxy is an HTTP proxy on proxy.example.com port 3128, you can run this:
```
java -Dhttps.proxyHost=proxy.example.com -Dhttps.proxyPort=3128 -jar okta-aws-cli-1.0.4.jar
```

Oracle's Java documentation on [Networking Properties § Proxies](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html#Proxies) may be useful for other experiments with this.

**Comment by AlainODea** [comment]
> Thanks, @AlainODea , I'll have a look. Also, recently we came across one more issue when one of our developer trying to use the Okta CLI for AWS from Ec2 Linux instance. He is able to generate the credentials, but when he executing the aws CLI commands it gives the access denied. I'm sure that he has required permissions for the role he generated the credentials. But still, he is not able to use them, seems like it assumes a different role than the one to be used.

He should try this to use a named profile and see what role he has assumed through Okta:

```
export OKTA_PROFILE=test
java -jar okta-aws-cli-1.0.4.jar com.okta.tools.WithOkta aws --profile test sts get-caller-identity
```

**Comment by AlainODea** [comment]
@naiduklr936 SOCKS proxy support is not fixed in v1.0.4. That's why #217 is still open. I'm waiting on a code review.
