### ISSUE TITLE
Error when assuming role in current organisation

### ISSUE THREAD

**Issue by novocodev** [oktadeveloper/okta-aws-cli-assume-role#21]
I am using this tool to assume a role in the same organisation as the user I use to access was via okta, when I run the tool I get an error.

My config looks like:

```
OKTA_ORG=domain.oktapreview.com
OKTA_AWS_APP_URL=https://domain.oktapreview.com/home/amazon_aws/0ia84r1fghTqB61ZR9h7/137
AWS_IAM_KEY=MYKEY
AWS_IAM_SECRET=MYSECRET
```

When I run the tool I get:

```
Username: my_okta_name
Password: my_okta_password

Please choose the role you would like to assume: 
[ 1 ]: arn:aws:iam::124546611879:role/Role_I_want_to_assume_in_same_org
Selection: 1
Exception in thread "main" com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: The security token included in the request is invalid. (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: 140d6651-c6a3-11e6-973b-81205f56c3d6)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:6882)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:6858)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getRole(AmazonIdentityManagementClient.java:3670)
	at com.okta.tools.awscli.GetRoleToAssume(awscli.java:435)
	at com.okta.tools.awscli.main(awscli.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

If I comment out line #119 `GetRoleToAssume(crossAccountRoleName);` in `awscli.java`, then the tool works correctly and generates temporary credentials that allow the aws cli to connect.

The issue seems to be that variable `crossAccountRoleName` gets set to the role name [1] selected above, which results in an attempt to assume a cross account role that does not exist, as this role is in the same organisation as the user.

Is there some additional config I can define to prevent the attempt to assume a cross account role?

**Comment by raphaellondner-okta** [comment]
Sorry for the late feedback and I apologize you've run into some issues. Can you please test with the fix available at https://github.com/oktadeveloper/okta-aws-cli-assume-role/tree/rl-configfile-fix/out? 

Just download the oktaawscli.jar updated file and please modify the log4j2.xml file to display

 <root level="debug">

instead of 

 <root level="error">

and please copy/paste the resulting messages you get if this fix still doesn't solve your issue.

**Comment by novocodev** [comment]
I ran the fix JAR and get the following exception, I ran with DEBUG logging but did not see any additional output. In the post above the specific logging config is missing.

Exception in thread "main" com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: The security token included in the request is invalid. (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: f7e8a81f-d199-11e6-a6fa-917389377f0d)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:6882)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:6858)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getRole(AmazonIdentityManagementClient.java:3670)
	at com.okta.tools.awscli.GetRoleToAssume(awscli.java:437)
	at com.okta.tools.awscli.main(awscli.java:119)

**Comment by raphaellondner-okta** [comment]
The line you should modify in the log4j2.xml is:

<root level="error">

and should instead mention:

<root level="debug">

Can you provide the additional output you get with that debug level?

**Comment by novocodev** [comment]
Here is the output:

```
10:17:03 [main] DEBUG com.okta.tools.awscli - Cross-account role is MySelectedRole
10:17:04 [main] DEBUG com.okta.tools.awscli - Creating the AWS Identity Management client
10:17:04 [main] DEBUG com.okta.tools.awscli - Getting role: MySelectedRole
Exception in thread "main" com.amazonaws.services.identitymanagement.model.AmazonIdentityManagementException: The security token included in the request is invalid. (Service: AmazonIdentityManagement; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: eef1a6b7-d266-11e6-b94f-5ffa7183f49a)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:6882)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:6858)
	at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getRole(AmazonIdentityManagementClient.java:3670)
	at com.okta.tools.awscli.GetRoleToAssume(awscli.java:437)
	at com.okta.tools.awscli.main(awscli.java:119)
```

**Comment by raphaellondner-okta** [comment]
We've been able to reproduce your specific issue by specifying an invalid AWS_IAM_KEY in the config.properties file. Can you please verify the AWS_IAM_KEY and AWS_IAM_SECRET values and try again with a new set of valid values?

**Comment by novocodev** [comment]
@raphaellondner-okta 

Ah, good spot, that was the issue, I had typed a '0' instead of a 'O' in the AWS_IAM_KEY.

**Comment by novocodev** [comment]
@raphaellondner-okta 

I have retested this with the latest binary from master branch and it is working as expected.
