### ISSUE TITLE
Issues working behind Proxy

### ISSUE THREAD

**Issue by NaveenAtCNA** [oktadeveloper/okta-aws-cli-assume-role#214]
**Describe the bug**

Tried this utility behind proxy, try to set the proxy different ways none of them seems to be working. 
1.	Set the proxy outside of the utility -Djava.net.useSystemProxies=true, then it gives the below error
2.      Also tried to set the proxy at the Java Path.

java -Djava.net.useSystemProxies=true -Dhttps.proxyHost=***.**.com -Dhttps.proxyPort=**** -classpath okta-aw
s-cli-1.0.2.jar com.okta.tools.awscli
Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:13 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:25 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {tls}->http://proxy.cna.com:8080->https
://cnapreview.okta.com:443: Malformed reply from SOCKS server
Sep 30, 2018 8:42:37 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {tls}->http://proxy.cna.com:8080->https://cnapreview.okta.com:443
Exception in thread "main" java.net.SocketException: Malformed reply from SOCKS server
        at java.net.SocksSocketImpl.readSocksReply(Unknown Source)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AlainODea** [comment]
I'm sorry for the frustration you are experiencing with proxies here.

A few questions:
1. What version of the JRE are you running?
2. What kind of proxy is proxy.cna.com:8080? (HTTP, SOCKSv4, SOCKv5)
3. Can you provide the complete stack trace of the error you are encountering?

Please validate your proxy's compatibility with Java as follows:

The following scripts can be pasted into jshell which is included with Java 9 or later. They'll show the proxy Java selects and the output of loading the test site through the proxy.

Test system proxies:

```java
var testSite = "https://cnapreview.okta.com/"
import java.net.*
import java.io.*
URI uri = URI.create(testSite)
System.setProperty("java.net.useSystemProxies", true)
ProxySelector.getDefault().select(uri)
new BufferedReader(new InputStreamReader(uri.toURL().openStream())).lines().forEach(System.out::println)
```

Test an HTTP proxy:

```java
var proxyHost = "proxy.cna.com"
var proxyPort = "8080"
var testSite = "https://cnapreview.okta.com/"
import java.net.*
import java.io.*
URI uri = URI.create(testSite)
System.setProperty("https.proxyHost", proxyHost)
System.setProperty("https.proxyPort", proxyPort)
ProxySelector.getDefault().select(uri)
new BufferedReader(new InputStreamReader(uri.toURL().openStream())).lines().forEach(System.out::println)
```

Test a SOCKS proxy:

```java
var proxyHost = "proxy.cna.com"
var proxyPort = "8080"
var testSite = "https://cnapreview.okta.com/"
import java.net.*
import java.io.*
URI uri = URI.create(testSite)
System.setProperty("socksProxyHost", proxyHost)
System.setProperty("socksProxyPort", proxyPort)
ProxySelector.getDefault().select(uri)
new BufferedReader(new InputStreamReader(uri.toURL().openStream())).lines().forEach(System.out::println)
```

If you are using Java 8, you can compile and run the following Java programs with the same JVM args as you are testing with okta-aws-cli (instructions for doing that are provided on the Gists):
* WhatIsMyProxy https://gist.github.com/AlainODea/6524270
* GetURL https://gist.github.com/AlainODea/6524217

**Comment by AlainODea** [comment]
@NaveenAtCNA scratch that. I've independently confirmed your bug report.

It looks like one of the HTTP clients the code is using doesn't support SOCKS proxies:
```
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://verafin.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://verafin.okta.com:443
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://verafin.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://verafin.okta.com:443
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://verafin.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://verafin.okta.com:443
Exception in thread "main" java.net.SocketException: Can't connect to SOCKS proxy:Connection refused (Connection refused)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.okta.tools.saml.OktaSaml.reuseSession(OktaSaml.java:137)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:37)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:123)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:93)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

I'll investigate. For the time-being I recommend enabling an HTTP proxy if possible or allowing a direct access exception.

**Comment by AlainODea** [comment]
@NaveenAtCNA scratch that. I've independently confirmed your bug report.

It looks like one of the HTTP clients the code is using doesn't support SOCKS proxies:
```
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://example.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://example.okta.com:443
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://example.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://example.okta.com:443
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://example.okta.com:443: Can't connect to SOCKS proxy:Connection refused (Connection refused)
Oct 01, 2018 11:00:19 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://example.okta.com:443
Exception in thread "main" java.net.SocketException: Can't connect to SOCKS proxy:Connection refused (Connection refused)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:428)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.okta.tools.saml.OktaSaml.reuseSession(OktaSaml.java:137)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:37)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:123)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:93)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

I'll investigate. For the time-being I recommend enabling an HTTP proxy if possible or allowing a direct access exception.

**Comment by AlainODea** [comment]
This looks promising:
https://stackoverflow.com/a/22960881/154527

It works with a SOCKS proxy for me. I'll have to figure out how to integrate this into the code without breaking use for every other non-proxy of HTTP-proxy config.

**Comment by NaveenAtCNA** [comment]
I overcome the Proxy issue now after setting the Proxy Settings in a different way. Now i see this issue.
I have access to AWS Console when I go using the Web Console, can you let us know what is the error for. In the config, i specified all these -

OKTA_ORG=*****
OKTA_AWS_APP_URL=******
OKTA_BROWSER_AUTH=false
OKTA_USERNAME=*****
OKTA_PASSWORD=
OKTA_AWS_ROLE_TO_ASSUME=******
OKTA_PROFILE=
OKTA_STS_DURATION=36000

Exception Trace -

U:\.okta>java -Dhttps.proxyHost=***.cna.com -Dhttps.proxyPort=**** -classpath okta-aws-cli-1.0.2.jar com.okta.tools.aw
scli -sts get-caller-identity
Username: ****
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:53)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:45)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
        at com.okta.tools.awscli.main(awscli.java:33)

**Comment by NaveenAtCNA** [comment]
Tried with 1.0.4 same error. Tried with OKTA_AWS_APP_URL in browser it works.

Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsFromDocument(OktaSaml.java:74)
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:53)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:120)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
        at com.okta.tools.awscli.main(awscli.java:41)

**Comment by AlainODea** [comment]
I suspect a proxy issue remains.

Please run this in jshell and comment back with what it outputs:

```java
var proxyHost = "proxy.cna.com"
var proxyPort = "8080"
var testSite = "https://signin.aws.amazon.com/saml"
import java.net.*
import java.io.*
URI uri = URI.create(testSite)
System.setProperty("socksProxyHost", proxyHost)
System.setProperty("socksProxyPort", proxyPort)
ProxySelector.getDefault().select(uri)
new BufferedReader(new InputStreamReader(uri.toURL().openStream())).lines().forEach(System.out::println)
```
