### ISSUE TITLE
Second try to enter token fails with null pointer exception

### ISSUE THREAD

**Issue by condemil** [oktadeveloper/okta-aws-cli-assume-role#215]
**Describe the bug**

When token verification fails the `java.lang.NullPointerException` error shows up after entering token again.

_Example 1:_

```
Username: ***@***.com

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
111111
Invalid Passcode/Answer
Please try again

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
932072
Exception in thread "main" java.lang.NullPointerException
	at com.okta.tools.authentication.OktaMFA.handleTimeoutsAndChanges(OktaMFA.java:77)
	at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:54)
	at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:38)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:44)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)
```

_Example 2:_

```
Username: ***@***.com

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
692106
Each code can only be used once. Please wait for a new code and try again.
Please try again

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
387212
Exception in thread "main" java.lang.NullPointerException
	at com.okta.tools.authentication.OktaMFA.handleTimeoutsAndChanges(OktaMFA.java:77)
	at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:54)
	at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:38)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:44)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:88)
	at com.okta.tools.awscli.main(awscli.java:33)
```

**To Reproduce**
1. Enter wrong token
2. Enter proper token
3. See error

**Expected behavior**
Verification pass after second try, error shouldn't show up.

**Additional context**
Version: 1.0.2

**Comment by AlainODea** [comment]
Thank you for your bug report @condemil. I'll validate this now.

**Comment by AlainODea** [comment]
Confirmed on v1.0.3.

```
Exception in thread "main" java.lang.NullPointerException
at com.okta.tools.authentication.OktaMFA.handleTimeoutsAndChanges(OktaMFA.java:77)
at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:54)
at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:75)
at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:46)
at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:106)
at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
at com.okta.tools.WithOkta.main(WithOkta.java:24)
```

**Comment by AlainODea** [comment]
@condemil v1.0.4 is released with a fix for this.
