### ISSUE TITLE
Unable to run this in a headless env

### ISSUE THREAD

**Issue by askldjd** [oktadeveloper/okta-aws-cli-assume-role#248]
**Describe the bug**
Using the latest release 1f1ef54c6f9d8d360906d17cc21697835a34ef8c, I am not able to run `okta-aws-cli.jar` in a headless environment.

**To Reproduce**
1. Create an AWS machine
1. Git clone this repo, and run `mvn package` 
1. Go to the `target` folder and verify that the jar file exist
1. Run `java -classpath ~/.okta/okta-aws-cli.jar com.okta.tools.WithOkta`
1. It will fail with the following error
```
$ java -classpath ~/.okta/okta-aws-cli.jar com.okta.tools.WithOkta
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
```

**Expected behavior**
I expect it to not fail.

**Screenshots**
Here's the full callstack
```
$ java -classpath ~/.okta/okta-aws-cli.jar com.okta.tools.WithOkta
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(GtkApplication.java:173)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:171)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

My java version
```
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by AlainODea** [comment]
@askldjd I haven't heard from you in a while. I'm going to close this. The fix is to set OKTA_BROWSER_AUTH environment variable to false on headless machines.
