### ISSUE TITLE
Crash encountered if password has expired

### ISSUE THREAD

**Issue by staticfox** [oktadeveloper/okta-aws-cli-assume-role#249]
**Describe the bug**
If a password has expired, the CLI crashes with a vague null pointer exception after the username, password, and MFA token have already been accepted.

**To Reproduce**
1. Ensure your password has expired
2. Run `awscli sts get-caller-identity`
3. Input your Username, Password, and Token

**Expected behavior**
Some form of description along with the stack trace that indicates the password has expired, perhaps similar to how https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/101 includes the `java.lang.RuntimeException: You do not have access to AWS through Okta.` bit.

**Additional context**
```
[matt@matt-dev ~]$ awscli sts get-caller-identity
Username: username@email.com
Password:

GOOGLE Token Factor Authentication
Enter 'change factor' to use a different factor
Token:
xxxxxx
Exception in thread "main" java.lang.NullPointerException
        at com.okta.tools.authentication.OktaMFA.handleTimeoutsAndChanges(OktaMFA.java:92)
        at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:69)
        at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:90)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:58)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:120)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
        at com.okta.tools.awscli.main(awscli.java:41)
```

Ran against release okta-aws-cli-1.0.6.jar

I realize that this is somewhat of a rare issue, but I typically only use the CLI when using Okta as I usually don't have a need to sign in to the web panel often. If this isn't something that can necessarily be resolved, then I totally understand. As always, feel free to let me know if I can provide any additional information. Thanks! :)

**Comment by AlainODea** [comment]
@staticfox thank you for your report. I will investigate this and see if I can get better diagnostics back from the authentication failure message.
