### ISSUE TITLE
Different operation procedure by operating system

### ISSUE THREAD

**Issue by kgangihv** [oktadeveloper/okta-aws-cli-assume-role#253]
**Describe the bug**
I work in an environment with users on Windows, Linux, and Mac.  I personally use Windows and Linux.  My Linux okta-aws client has been great and life saving, so thank you.  My Windows usage has been troublesome to say the least.  Running "okta-aws test sts get-caller-identity" on Windows, brings up the java "browser" just fine but it always gives me an error message.  I've copied the same URL into all the different browsers I have installed and have never had an issue logging in...only with the java "browser".

Also, on Linux, when commenting out OKTA_BROWSER_AUTH, it returns asking for my username/password.  It does not work the same way in Windows Powershell.

**To Reproduce**
1. Follow instructions to install okta-aws-cli-assume-role
2. Set OKTA_ORG, OKTA_AWS_APP_URL, OKTA_USERNAME, and OKTA_BROWSER_AUTH
3. (Secure environment) Start PowerShell Run...,  powershell –ExecutionPolicy Bypass
4. okta-aws test sts get-caller-identity, this opens up the java "browser"
5. Type in username and password.  
6. Get an error.  "We found some errors.  Please review the form and make corrections."

**Expected behavior**
At this point, the browser should kick me to the AWS page where I can select the profile I would like to login as.  (I have multiple profiles)
If I comment out the OKTA_BROWSER_AUTH parameter, I expect the command to work like Linux where it prompts me for my username/password.

**Screenshots**
Browser issue:
![image](https://user-images.githubusercontent.com/44781067/50016487-52da8f80-ff97-11e8-853a-c71dda2ab764.png)

CMD line issue:
![image](https://user-images.githubusercontent.com/44781067/50016929-97b2f600-ff98-11e8-8368-b0f3fba863f4.png)

CMD working in Linux:
![image](https://user-images.githubusercontent.com/44781067/50017002-d47eed00-ff98-11e8-8538-68c7483f5b11.png)
As you can see, I definitely have access to AWS through OKTA.

**Additional context**
My system is running Windows 10 ENT 10.0.17134 Build 17134, and my java version if 8u191 64bit.

**Comment by AlainODea** [comment]
What happens normally is that the embedded browser loads the AWS SAML Sign-in page, parses it, and then presents the role selection menu (unless you have already specified a role for the **kgangi** profile).

Does the secure environment have a proxy for the browser to use?

NOTE: It the browser obtains the proxy from a PAC, this tool won't make use of that proxy. PAC is not supported and you'll need to entry your proxy information manually into the Internet Options dialog.

## Why I think it is a proxy issue
This error message is a fallback for when the tool can't find a properly formatted Okta error message:
```
You do not have access to AWS through Okta. 
Please contact your administrator.
```

It's not a great error message, and I suppose it might be better to echo the response document to the console in this case.

To me, given that the same URL works locally, it indicates that there may be a middlebox of some kind returning a 1XX-3XX HTTP status code and an HTML page that doesn't contain the SAMLResponse.

**Comment by kgangihv** [comment]
I guess I should have talked more about the environment.  I am on the Operations team...so I have admin right to my Windows 10 laptop, I also have a fedora 29 instance running on the same laptop in VirtualBox.  We are becoming more "secure"...but we aren't that secure just yet.
I understand why it seems like a proxy issue but I can confirm it is not.

<img width="330" alt="proxysettings" src="https://user-images.githubusercontent.com/44781067/50026739-03f12200-ffb8-11e8-8925-0d62a212e76d.PNG">

Is there anything I can do...maybe a debug flag from my perspective?
On my linux laptop, the application works like a charm...java apps should work everywhere the same right?  (joking)

**Comment by AlainODea** [comment]
Regrettably beyond going all the way to jdb or a Java debugger in Eclipse or IntelliJ, there aren’t good debug options for this right now. We’ve been gradually adding better diagnostics and I think one of those would be to log that entire unexpected document instead of just the placeholder error message.

It is very surprising to me that the embedded browser doesn’t work for you. It clearly doesn’t and I don’t doubt that. I’m just trying to reason through why. We use it in a secure enclave on Windows with very restricted outbound proxy access and it works seamlessly. We also used the pure command line approach for months before the browser was added.

**Comment by AlainODea** [comment]
Another possible solution is clearing the state. It may have a partially auth'd session stored.

Try this:

```shell
Remove-Item ~\.okta\cookies.properties
Remove-Item ~\.okta\profiles
Remove-Item ~\.okta\.current_session
```

And then retry the Windows auth with OKTA_BROWSER_AUTH commented out.

**Comment by AlainODea** [comment]
@kgangihv you can rebuild this and try with the enhanced logging I've added in 13bccfe. I'll cut a release in early 2019.

**Comment by AlainODea** [comment]
@kgangihv any luck?

**Comment by AlainODea** [comment]
The blank window is expected.

Normally that window would display the “signing into Amazon Web Services” loading screen for your Okta org, but it happens so quickly that JavaFX can’t render it before the browser is closed.

You already have a session so it just grabs the SAMLResponse from the response before the loader spinner can render.

**Comment by kgangihv** [comment]
Hi,

Ignore that last message...we were on break for a week and a half.  I made a backup of the .okta dir and was looking at the config for that directory.

I get the same message as before when using the web browser.  When I set the browser auth to false, I get:

PS C:\Users\kgangi> okta-aws kgangi-dev sts get-caller-identity
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems, Inc"
Exception in thread "main" java.lang.RuntimeException: You do not have access to AWS through Okta.
Please contact your administrator.
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsFromDocument(OktaSaml.java:87)
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:71)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:56)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:120)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:90)
        at com.okta.tools.WithOkta.main(WithOkta.java:28)

**Comment by AlainODea** [comment]
Have you built the new version based on master? I don’t have a release with the improved diagnostics yet. I can cut one this weekend if you’d rather wait.

**Comment by kgangihv** [comment]
Sorry...again...if I only paid attention to the words you were typing...

Yes, I just built it...and I have some mildly useful data.  See attached file.
[error.log](https://github.com/oktadeveloper/okta-aws-cli-assume-role/files/2728521/error.log)

**Comment by AlainODea** [comment]
> Your registration is almost complete! Check your inbox for an Activation Email and follow the instructions before you can log in to Hitachi Vantara secured websites.

I think it’s a captive portal of some kind.

**Comment by AlainODea** [comment]
My mistake. This page comes from your Okta Org directlyz

It’s email auth in Okta itself. I don’t think I have that feature, but I’ll check.

**Comment by AlainODea** [comment]
[Okta Device Trust](https://help.okta.com/en/prod/Content/Topics/Mobile/device-trust.htm) might be enforced, which would explain why it works in a full browser and not the embedded browser or CLI client.

The Device Trust flow hasn't been tested with this tool. It is quite involved to set up Device Trust and would involve significant code changes here to have the embedded browser and CLI client load the appropriate certificate and perform mutual TLS client auth when prompted.

**Comment by kgangihv** [comment]
I guess this is a possibility.  The only thing I can think of to dispute that is that my Windows laptop would be the secure “trusted” device.  The IT team would know nothing of my linux box.  The CLI works great from my linux box.  That is the weird part about this whole thing.

**Comment by AlainODea** [comment]
The Okta configuration allows enforcement of different policies by client type and origin network. It is possible that Device Trust is enforced only for Windows.  

![image](https://user-images.githubusercontent.com/16341/50776586-ed1ab400-1273-11e9-8650-589336e13468.png)
