### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException: text

### ISSUE THREAD

**Issue by tylerlong** [oktadeveloper/okta-aws-cli-assume-role#260]
```
java -classpath ~/.okta/okta-aws-cli-1.0.7.jar com.okta.tools.awscli sts get-caller-identity
```

```
➜  ~ ~/.okta/aws-token
Exception in thread "main" java.lang.NullPointerException: text
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1945)
	at java.base/java.time.Instant.parse(Instant.java:395)
	at com.okta.tools.aws.settings.MultipleProfile.getExpiry(MultipleProfile.java:56)
	at com.okta.tools.aws.settings.MultipleProfile.getProfile(MultipleProfile.java:43)
	at com.okta.tools.helpers.SessionHelper.lambda$getFromMultipleProfiles$1(SessionHelper.java:98)
	at com.okta.tools.helpers.FileHelper.readingPath(FileHelper.java:129)
	at com.okta.tools.helpers.SessionHelper.getFromMultipleProfiles(SessionHelper.java:97)
	at com.okta.tools.OktaAwsCliAssumeRole.init(OktaAwsCliAssumeRole.java:76)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:80)
	at com.okta.tools.awscli.main(awscli.java:41)
```

**Comment by AlainODea** [comment]
Is this a new failure since v1.0.6? (aka does v1.0.7 introduce a breaking change I missed?)

I’ll look into this either way, but I’m wondering if I need to pull or caveat v1.0.7.

**Comment by AlainODea** [comment]
My pleasure, @tylerlong. I'm glad it worked.
