### ISSUE TITLE
Unable to open DISPLAY when I execute awscli

### ISSUE THREAD

**Issue by erlchamp** [oktadeveloper/okta-aws-cli-assume-role#265]
Am getting this error...
```
root@donw-erlchamp-04:~/.okta# awscli
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:68)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:41)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:257)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:211)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
root@donw-erlchamp-04:~/.okta# java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

Linux donw-erlchamp-04 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I've installed OpenFX as well.
OKTA_BROWSER_AUTH is also in my ~/.okta/config.properties

**Screenshots**
![image](https://user-images.githubusercontent.com/37998321/51163141-af510780-18d3-11e9-84e2-60ec5df6ad09.png)

**Comment by AlainODea** [comment]
Try setting OKTA_BROWSER_AUTH=false in config.properties to turn off the features that need DISPLAY. This will break support for app-level MFA, app-level sign-on policies, and prompts for re-authentication.

Alternatively, you could get a usable DISPLAY by forwarding the X11 session. You’ll need to research and troubleshoot that yourself. I haven’t tried it. ssh -X is related to that.

**Comment by erlchamp** [comment]
It worked perfectly! btw, can I confirm that one of the pre-requisites of integrating AWS cli to OKTA is to create IAM users first?

Thanks @AlainODea

**Comment by AlainODea** [comment]
IAM users are not required for each user. This tool creates named temporary AWS STS sessions.

Only a single IAM User (named **OktaSSOUser** in the setup instructions) is required for the Okta Admin console to download the set of usable IAM Roles.

Comprehensive instructions for setting up Okta and AWS to work together are provided by clicking the **View Setup Instructions** button in the **Sign On** tab of your **Amazon Web Services** app in the Okta admin console. I suggest following **Connect Okta to Multiple AWS Instances** section to work best with this tool.
