### ISSUE TITLE
Unable to authenticate through browser or cli

### ISSUE THREAD

**Issue by Nyefan** [oktadeveloper/okta-aws-cli-assume-role#271]
**Describe the bug**
When using the following `config.properties`

```
OKTA_ORG=<my_org>.okta.com
OKTA_AWS_APP_URL=https://my_org.okta.com/home/amazon_aws/token/three_numbers
OKTA_BROWSER_AUTH=false
```

I receive the following error message before the program crashes:

```java
Exception in thread "main" java.lang.RuntimeException: An unhandled error occurred. Please consult the server response above.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsFromDocument(OktaSaml.java:79)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:62)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

with the server response at the bottom of this post.

When doing the same with `OKTA_BROWSER_AUTH=true`, I reach the correct login page, but completing the form there doesn't trigger `USER_AUTH_COMPLETE.countDown()`, and the jfx browser continues to the fully functional AWS console for my organization.  Once I close the window, withOkla exits(1) without creating a profile or requesting a temporary awscli key and secret.

**Additional context**

A couple flags I noticed and tried to work with before bringing this up:

- The login form is never rendered in the cli-only variation of the authflow, but it is both rendered and fully functional in the browser version.  
- Naively changing `OktaSaml.getSamlResponseForAwsFromDocument()` to retrieve `SigninToken` just results in a base64 conversion error.
- Altering `OktaSaml.isPasswordAuthenticationChallenge()` or `OktaSaml.isProptForFactorChallenge()` to `return true` results in an infinite loop with the same page being returned each time the initial request is retried with the new auth parameters.
- Enabling noscript and then navigating to the OKTA_AWS_APP_URL in my browser results in this same page being returned.

```html
<!doctype html>
<html lang="en">
 <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="robots" content="noarchive">
  <meta name="googlebot" content="noarchive">
  <meta name="robots" content="noindex"> 
  <meta http-equiv="X-UA-Compatible" content="IE=Edge"> 
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="googlebot" content="noindex"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
  <meta name="robots" content="none"> 
  <link href="https://ok2static.oktacdn.com/assets/img/icons/favicons/favicon-16x16.c55b69ae49b08edc7c000d12b8e5483f.png" rel="icon" type="image/png" sizes="16x16">
  <link href="https://ok2static.oktacdn.com/assets/img/icons/favicons/favicon-32x32.99bc356b6e293b927f9e3a2b69761c26.png" rel="icon" type="image/png" sizes="32x32">
  <link href="https://ok2static.oktacdn.com/assets/img/icons/favicons/favicon-96x96.de98828614fa33ca04fcfaa07679f345.png" rel="icon" type="image/png" sizes="96x96">
  <meta name="msapplication-TileColor" content="#ffffff"> 
  <meta name="msapplication-TileImage" content="/img/icons/favicons/ms-icon-144x144.png"> 
  <meta name="application-name" content="Okta"> 
  <meta name="theme-color" content="#ffffff"> 
  <meta name="msapplication-config" content="/img/icons/favicons/browserconfig.xml"> 
  <title>MyOrg - Signing in...</title> 
  <!--[if IE]><link href="https://ok2static.oktacdn.com/assets/css/ie/ie.dfbe39884a139eeaa652e6b1ce8fc198.css" type="text/css" rel="stylesheet"/><![endif]--> 
  <!--[if IE 7]><link href="https://ok2static.oktacdn.com/assets/css/ie/ie7.00cf245ce935958a8872ed5b16754ffa.css" type="text/css" rel="stylesheet"/><![endif]--> 
  <!--[if IE 8]><link href="https://ok2static.oktacdn.com/assets/css/ie/ie8.ab88bee11dc4e5fc665dd656aa481ced.css" type="text/css" rel="stylesheet"/><![endif]--> 
  <!--[if lte IE 8]><link href="https://ok2static.oktacdn.com/assets/css/ie/ie-user-states.c5d8b475ffffc4eddd5443901a30ce35.css" type="text/css" rel="stylesheet"/><![endif]--> 
  <!--[if gte IE 9]><link href="https://ok2static.oktacdn.com/assets/css/ie/ie9.2e6d4e6712ae809a0b9259d91cf16475.css" type="text/css" rel="stylesheet"/><![endif]--> 
  <script>if (typeof module === 'object') {window.module = module; module = undefined;}</script> 
  <script>
    var okta = {
        migrateMute: true,
        locale: 'en',
        debug: false,
        deployEnv: 'ENV',
        userId: 'UserId',
        settings: {
            orgId: 'OrgId',
            orgName: 'MyOrg',
            serverStatus: 'ACTIVE',
            persona: '',
            isDeveloperConsole: '' === 'true',
            isPreview: 'false' === 'true',
            permissions: []
        },
        logHasFeatureError: function(message) {
            var xhr = new XMLHttpRequest();
            xhr.open('POST', '/api/internal/client-logging/has-feature-error', true);
            xhr.setRequestHeader('Content-Type', 'application/json');
            xhr.send(JSON.stringify({
              message: message
            }));
        }

    };
</script> 
  <script>var _features=["ADMIN_EMAILS_BCC","FAST_MASTER_PRIORITY_FETCH","O365_MODERN_AUTH_WEB_DISTINCTION_FILTER","DEFAULT_ENTITLEMENTS_MAPPING","AUTOMATIC_UD_PROFILE_MIGRATION","MONTHLY_FLAG_2018_10","PHONE_CALL_FACTOR","OKTA_GROUP_MEMBERSHIPS_V2_WRITES","NEW_SIGN_IN_MIGRATION","SKIP_IMPORT_USER_WITHOUT_EXTERNAL_ID","ELASTICSEARCH_NEUSTAR_IP_DATA","PASSWORD_POLICY_SOFT_LOCK","USG_EXTERNAL_ORG_ID_KEY","MULTIPLE_NETWORK_ZONES","OKTA_THREAT_INSIGHTS_DATA_COLLECTION","UD_ENABLED_APP_ASSIGNMENT_UI","APP_INSTANCE_ADMINISTRATION","MONTHLY_FLAG_2018_11","BATCH_IMPORTS_REFERENCE_COUNT","USE_PROPER_USER_PERMISSIONS","INTERNATIONAL_SMS","READ_EVENT_API_DATA_FROM_SAGE","PROV_JIRA_GROUP_PUSH_ENHANCEMENTS","CREATE_AAD_SERVICE_PRINCIPAL_FOR_OFFICE_365","PROV_ULTIPRO_WRITE_BACK_FOR_GLOBAL_EMPLOYEES","ADVANCED_SSO","LDAP_PASSWORD_RESET","MFA_SOFT_LOCK_FOR_DELAUTH_USERS","PENDING_USER_UX_CHANGES","UNRESTRICTED_APP_CREATION","SAML11_TEMPLATE_APP_FETCH_CUSTOM_ATTRIBUTES","UD_INBOUND_SAML_SHARED_ACS","MFA_SECURITY_QUESTION_FACTOR","ENG_OKTA_WINDOWS_VERIFY","DUO_SECURITY_FACTOR","YUBIKEY_FACTOR","CLEAR_UNCONFIRMED_IMPORTED_USERS","NETWORK_ZONES","PLUGIN_AUTH_FAILURE_DETECTION","PRODUCT_FEATURE_TRIAL_UI","ADMIN_APPS_LIST","OKTA_VERIFY_FACTOR_WITH_PUSH","PEOPLE_PAGE_PERF_IMPROVEMENT","DEPRECATE_PASSWORD_HANDLER_USAGE_IN_APP_DEL_AUTH_ENDPOINT","PLUGIN_ON_THE_FLY_APP_ADDITION","SWA_SIGNON_ADMIN_SETS_CREDENTIALS","UD_DEFINE_ENUM_PROPERTIES","AD_INSTANCE_DELAUTH","APP_NOTES","SEND_EMAIL_FOR_SIGNON_FROM_NEW_DEVICE","CDN_CONTENT_ENABLED","ONE_PAGE_MFA_FACTORS_UI","MONTHLY_FLAG_2019_01","HANDLE_MULTIPLE_VALUES_IN_REDIRECT_URL","USE_ORGNAME_AS_ISSUER_IN_QRCODE","IN_PRODUCT_HELP","TWILIO_MESSAGING_SERVICE_CAPABLE_SMS_API","PLUGIN_DISCOVERY_ENDPOINT","GROUP_MEMBERSHIP_RULES","PLUGIN_NEW_PAGE_MONITORING","ALLOW_6_MONTH_V1_V2_QUERIES","ENG_READ_PARTITIONED_TABLE_APP_USER_ACTIVITY","CLIENT_ACCESS_POLICY_MOBILE_PLATFORM_GRANULARITY","DISABLE_NEW_SIGNIN_FLOWS_TOGGLE","GROUP_PUSH_ENHANCEMENTS_ADOBE_CQ","CUSTOM_EMAIL_SENDER_SETTINGS","ENG_USE_CACHED_POLICIES_FOR_EVALUATION","TRUSTED_ORIGINS_UI","AD_PASSWORD_RESET","DELETE_AD_DOMAIN_USING_SID","EXTENSIBLE_PROFILE_ENCRYPTION","ADMIN_SITE_COOKIE_WITH_HTTPONLY","EVENTS_API_APPLY_RECENCY_FILTERING","OKTA_VERIFY_AUTO_PUSH","ONPREM_PROVISIONING","USER_SITE_COOKIE_WITH_HTTPONLY","PROV_SALESFORCE_COMMUNITY_AND_PORTAL","MONTHLY_FLAG_2018_09","DOCUSIGN_ENABLE_UD","TOUCHID_FOR_OKTA_VERIFY","VALIDATE_FACTOR_FOR_SESSION_AFTER_PUSH_ENROLLMENT","ENG_WRITE_DB_EVENTS_ASYNC","RUM_GROUP_PUSH_ENHANCEMENTS","AD_UD_TEMPLATE_MIGRATION","PROFILE_MASTER_USER_LIFECYCLE_SETTINGS","RUM_GROUP_PUSH_ADD_AND_REMOVE_ONLY","ENG_APPUSER_VISIT_BATCH_BY_STATUS_WITH_HINT","ENABLE_PER_USER_RATE_LIMITS","ENG_ACCOUNT_CHOOSER_PUBLISH","ALLOW_SWA","ADMIN_MANAGED_TABS_FIX_RACE_CONDITION","ENABLE_DELAUTH_TIMEOUT_TO_CACHE_REDIRECT","OFFICE365_DO_AUTH_ONLY","ENG_DUPLICATED_APPGROUPS_FIX","ADMIN_EMAIL_SETTINGS","CONSOLIDATE_USERNAME_EL","BASIC_SSO","AD_ADMIN_PASSWORD_RESET","APP_PROFILE_MASTERS","EXTENSIBLE_PROFILE_ENCRYPTION_APP_USER","ADMIN_MANAGED_TABS","MONTHLY_FLAG_2018_08","USER_MANAGEMENT","ENG_REPORTS_RESTRICT_QUERY_START_DATE","IWA_CUSTOM_ERROR_URL","OKTA_MFA_POLICY","VERIFY_PASSWORD_WHEN_MINTING_OAUTH_TOKEN","MAKE_ADMIN_APP_IMPLICIT","SECURID_FACTOR","SELF_SERVICE_CONSOLIDATION","AD_ADVANCED_BATCH_IMPORTS","APP_REQUEST_APPROVAL_WORKFLOW","DISABLE_ASYNCHRONOUS_USER_DELETE","OKTA_VERIFY_FACTOR","OM_TOUCHID_IOS","MFA_LIFECYCLE_EMAILS","SAGE_SAVED_SEARCH","ENG_UD_ENABLE_LOCALE_VALIDATION","RPC_DATA_ENCRYPTION_IN_REDIS","CUSTOM_EMAILS_MULTILANGUAGE_TEMPLATES","JIRA_USE_REST_FOR_GROUPS","ATTRIBUTE_LEVEL_MASTERING","SAML2_SHA2_CERTS","GROUP_PUSH_ENHANCEMENTS","VALIDATE_IDP_SCHEMA","ACCOUNT_LOCKOUT_USER_EMAIL","APP_SIGNON_QUERY_PARAM_FIX","DEPROVISIONING_WORKFLOW","GROUP_PASSWORD_POLICY","NEW_FEATURE_UI","OM_FINGERPRINT_ANDROID","APP_SPECIFIC_PASSWORD_POLICY","ENG_COUPA_DISABLE_JERSEY_CLIENT","O365_APP_SIGN_ON_CLIENT_FILTERS","API_RESPECT_SEND_EMAIL_PARAMETER_ON_DEACTIVATE","X_FORWARDED_FOR_VALIDATION","ENG_EVENT_V1_STREAM_ELASTICSEARCH","ASYNC_REPORT_LIST_PAGE_IN_ADMIN_APP","INBOUND_SAML","GROUP_RULES_FOR_MULTIPLE_GROUPS","BATCH_ALL_DEACTIVATION_EMAILS","FEATURE_HISTORY_PAGE","NEW_SIGNIN_FLOWS","AUTH_WHITELIST_URLS","ORG_SPECIFIC_ADMIN_BANNER","SEND_USER_LOCKED_OUT_EMAIL_TO_RELEVANT_ADMINS_ONLY","NEW_INTERSTITIAL_PAGE","SMS_SERVICE","LDAP_PASSWORD_RESET_SMS","AD_FORGOT_PASSWORD","UD_INBOUND_SAML","ADMIN_MANAGED_TABS_OPTIMIZE_DB","REMOVE_LEGACY_CREATE_USER_MODAL","ENG_ENABLE_EMAIL_RATE_LIMIT","EXTENSIBLE_PROFILE_ENCRYPTION_RESOURCE_REQUEST","OKTA_INTERSTITIAL_SETTINGS","LINKED_OBJECT_PROPERTIES","SYMANTEC_VIP_FACTOR","MFA_SOFT_TOKEN_FACTOR","OTHER_APP_SIGN_ON_CLIENT_FILTERS","MONTHLY_FLAG_2018_12","U2F_AS_A_FACTOR","ENG_MITIGATE_MALFORMED_REDIRECT_URL","OKTA_GROUP_PROFILES_V2_WRITES","RESTRICT_VIEW_SHARED_PASSWORD_FOR_APP"];</script>
  <script>window.okta || (window.okta = {}); okta.cdnUrlHostname = "//ok2static.oktacdn.com"; okta.cdnPerformCheck = false;</script>
  <script>window.okta || (window.okta = {});window.okta.mixpanel = true;window.okta.mixpanelTrackingSamplingFactors = {"_DEFAULT":1.0};</script>
  <script src="https://ok2static.oktacdn.com/assets/js/jquery-1.12.4.min.e93c5a2265fbe2a3e96fe19159fc9a84.js?v=1" type="text/javascript"></script>
  <!--[if lt IE 9]><script src="https://ok2static.oktacdn.com/assets/enduser/js/vendor/css3-mediaqueries.fa295f0132f5335f352071ca3613a94a.js?v=1" type="text/javascript"></script><![endif]--> 
  <script>if (window.module) module = window.module;</script> 
 </head> 
 <body id="app" class="enduser-app  "> 
  <noscript>
   <div id="noscript-mask"></div>
   <div id="noscript-msg" class="infobox infobox-warning infobox-compact">
    <span class="icon warning-16"></span>
    <h3>Javascript is disabled on your browser.</h3>
    <p>Please enable Javascript and refresh this page to use Okta.</p>
   </div>
  </noscript> 
  <div id="container"> 
   <link href="https://ok2static.oktacdn.com/assets/css/sections/interstitial.c22f9cc988086c3b50de2f50b83669e5.css" type="text/css" rel="stylesheet">
   <!--[if lte IE 9]>
            <style type="text/css">
                #okta-auth-spin {
                    top: 35%;
                }
            </style>
        <![endif]--> 
   <!--[if lte IE 8]>
            <style type="text/css">
                #okta-auth-band {
                    height: 200px;
                }
            </style>
        <![endif]--> 
   <div id="okta-interstitial-wrap"> 
    <div class="okta-auth-mask-new-interstitial"></div> 
    <div class="new-interstitial" id="new-interstitial"> 
     <div id="okta-auth-band"> 
      <img src="https://ok2static.oktacdn.com/assets/img/ui/indicators/new_interstitial_static.1234567890a.png" width="376" height="160" alt="Please wait" class="new-img-static">
      <img src="https://ok2static.oktacdn.com/assets/img/ui/indicators/new_interstitial.c41c3b6f3a84458aca9a5919f238fbe3.gif" width="376" height="160" alt="Please wait" class="new-img">
      <img src="https://ok2static.oktacdn.com/assets/img/logos/okta_watermark.4a7f2ccf7d0a787cff6f59fb67f72843.png" width="106" height="36" alt="Okta" class="okta-logo">
      <div id="okta-auth-spin"></div> 
      <div id="okta-auth-spin-small"></div> 
      <h1 id="okta-auth-heading" class="signing-in-text">Signing in to AWS - Prod</h1> 
     </div> 
    </div> 
    <!--new-interstitial --> 
   </div> 
   <!--okta-interstitial-wrap --> 
   <script type="text/javascript">
            $(function(){
                var isFFSVGFixEnabled = 'false';
                if ($('#okta-auth-spin').hasClass('android-spinner')) {
                    return;
                }

                // Remove gif animation for Safari
                var isSafari = /AppleWebKit/.test(navigator.userAgent) && !/Chrome/.test(navigator.userAgent) && /Apple Computer/.test(navigator.vendor);
                if (isFFSVGFixEnabled && isSafari) {
                    $('.new-img').hide(0);
                } else {
                    $('.new-img').on('load', function(evt){
                        //gif loaded correctly, fade out static asset and fade in gif
                        //making sure we show the graphic before the form submit happens in 200ms
                        $('.new-img-static').hide(0,function(){
                            $('.new-img').show(0);
                        });
                    });
                }

                //For cached images with src the load event fires just before you add a listener for it. Hence setting the source again to make sure the event handlers fire in the right order.
                var assetUrl = $('.new-img').attr('src');
                $('.new-img').attr('src', assetUrl);

                var standard = document.getElementById('okta-auth-spin');
                var small = document.getElementById('okta-auth-spin-small');

                var optsStandard = {
                    lines: 9, // The number of lines to draw
                    length: 0, // The length of each line
                    width: 8, // The line thickness
                    radius: 21, // The radius of the inner circle
                    corners: 1, // Corner roundness (0..1)
                    rotate: 0, // The rotation offset
                    direction: 1, // 1: clockwise, -1: counterclockwise
                    color: '#fff', // #rgb or #rrggbb
                    speed: 1, // Rounds per second
                    trail: 60, // Afterglow percentage
                    shadow: false, // Whether to render a shadow
                    hwaccel: false, // Whether to use hardware acceleration
                    className: 'okta-auth-spinner', // The CSS class to assign to the spinner
                    zIndex: 2e9, // The z-index (defaults to 2000000000)
                    top: 'auto', // Top position relative to parent in px
                    left: 'auto' // Left position relative to parent in px
                };

                var optsSmall = {
                    lines: 9, // The number of lines to draw
                    length: 0, // The length of each line
                    width: 6, // The line thickness
                    radius: 14, // The radius of the inner circle
                    corners: 1, // Corner roundness (0..1)
                    rotate: 0, // The rotation offset
                    direction: 1, // 1: clockwise, -1: counterclockwise
                    color: '#fff', // #rgb or #rrggbb
                    speed: 1, // Rounds per second
                    trail: 60, // Afterglow percentage
                    shadow: false, // Whether to render a shadow
                    hwaccel: false, // Whether to use hardware acceleration
                    className: 'okta-auth-spinner', // The CSS class to assign to the spinner
                    zIndex: 2e9, // The z-index (defaults to 2000000000)
                    top: 'auto', // Top position relative to parent in px
                    left: 'auto' // Left position relative to parent in px
                };
                if (typeof Spinner === 'function') {
                    var spinnerStandard = new Spinner(optsStandard);
                    var spinnerSmall = new Spinner(optsSmall);

                    spinnerStandard.spin(standard);
                    spinnerSmall.spin(small);
                }

            });
        </script> 
   <form id="appForm" action="https://signin.aws.amazon.com/federation" method="GET" data-okta-status=""> 
    <input type="hidden" name="Action" value="login"> 
    <input type="hidden" name="Issuer" value="http://www.okta.com/"> 
    <input type="hidden" name="Destination" value="https://console.aws.amazon.com/"> 
    <input type="hidden" name="SigninToken" value="<!--SigninToken-->"> 
   </form> 
   <script type="text/javascript">
  $(function(){
      setTimeout(function(){
          document.getElementById('appForm').submit();
      }, 200);
  });
</script> 
  </div>
 </body>
</html>
```

**Comment by AlainODea** [comment]
Thank you for the detailed report, @Nyefan.

I think I see the problem. The code here looks for a form POSTing to **https://signin.aws.amazon.com/saml** and your Okta Amazon Web Services app being POSTed to **https://signin.aws.amazon.com/federation**.

Are you using the Okta Application Network-provided Amazon Web Services app or did you configure it directly using a generic Okta SAML app?

Either way there's a bug in this code in that a working Assertion Consumer Service URL for AWS isn't usable.

**Comment by Nyefan** [comment]
I have confirmed with our Okta admin that we are using the former.

**Comment by AlainODea** [comment]
> I have confirmed with our Okta admin that we are using the former.

I interpret that to mean you are using the Okta Application Network-provided Amazon Web Services app.

There is no **SAMLResponse** on the page this tool is getting back when it loads your OKTA_AWS_APP_URL. I suspect that setting is subtly incorrect. Your Okta administrator can get the correct link for you from the Embed link field in the App Embed Link section of the General tab and the  Amazon Web Services app in Okta Admin. Again, it has to be the real AWS app, and not a bookmark app.

The OKTA_AWS_APP_URL should be like **https://acmecorp.oktapreview.com/home/amazon_aws/0oa5zrwfs815KJmVF0h7/137** (note the /home/amazon_aws/) and it needs to be the real Amazon AWS Okta app and not a bookmark app.

A URL like **https://acmecorp.oktapreview.com/home/bookmark/0oa5zrwfs815KJmVF0h7/137** (note the /home/bookmark/) will not work.

**Comment by AlainODea** [comment]
I’m going to assume this is resolved.
