### ISSUE TITLE
Allow okta_sts_duration parameter per role, to allow multi session duration configurations.

### ISSUE THREAD

**Issue by tmann-fuze** [oktadeveloper/okta-aws-cli-assume-role#283]
The okta_sts_duration parameter is a huge benefit to enable roles with longer session durations, however if a user has multiple roles which do not all match, the user will receive an error when trying to assume a role with shorter duration than what's configured in okta config. 

For example, when a user selects a role with 1hr timeout, but has okta_sts_duration for 12hrs (used for other roles), oktacli will fail.  The only work around is to remove the sts_duration parameter, but this causes all roles to fallback to default 1hr session durations.

```
Exception in thread "main" com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: The requested DurationSeconds exceeds the MaxSessionDuration set for this role. (Service: AWSSecurityTokenService; Status Code: 400; Error Code: ValidationError; Request ID: efaa3d2b-4739-11e9-ba5e-a98f12265e9d)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1660)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1324)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1369)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1338)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1327)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRoleWithSAML(AWSSecurityTokenServiceClient.java:656)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRoleWithSAML(AWSSecurityTokenServiceClient.java:627)
	at com.okta.tools.helpers.RoleHelper.assumeChosenAwsRole(RoleHelper.java:39)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:133)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

It would be great if there was a way to flag certain roles with different sts_duration values.  It could be based on ARN perhaps?  If they're configured in a config, the sts will take the value for that role.  If not, it will use the global okta_sts_duration parameter.

In our environment, our users have many roles for various applications and not all roles require long sessions 1hr+ (production roles), however some do (development roles).  It would be great if we could configure based on need, and not an "all or nothing", type of thing.

**Comment by AlainODea** [comment]
@tmann-fuze this is a very good idea. Thank you. I've definitely been bitten by this.

**Comment by AlainODea** [comment]
An immediate workaround on v1.0.10 is this:

On PowerShell (Windows typically):

```powershell
$env:OKTA_STS_DURATION=3600
okta-aws one-hour-profile sts get-caller-identity
$env:OKTA_STS_DURATION=14400
okta-aws four-hour-profile sts get-caller-identity
aws --profile one-hour-profile s3 ls
aws --profile four-hour-profile ec2 describe-instances
```

On Bash (macOS/Linux/*nix-likes typically):

```bash
export OKTA_STS_DURATION=3600
okta-aws one-hour-profile sts get-caller-identity
export OKTA_STS_DURATION=14400
okta-aws four-hour-profile sts get-caller-identity
aws --profile one-hour-profile s3 ls
aws --profile four-hour-profile ec2 describe-instances
```

**Comment by tmann-fuze** [comment]
@AlainODea - Thank you for the workaround. We'll give this a try!
