### ISSUE TITLE
Ubuntu 16.04 Command line got https: Name or service not known

### ISSUE THREAD

**Issue by lzhengqc** [oktadeveloper/okta-aws-cli-assume-role#286]
I followed https://github.com/oktadeveloper/okta-aws-cli-assume-role and https://support.okta.com/help/s/article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta installed okta-aws-cli in ubuntu 16.4 server. 

- Java version is 1.8 
- AWS cli version is 1.16.131
- okta aws cli version 2.0.0
- Ubuntu 16.04 server

config.properties has **OKTA_ORG** and **OKTA_AWS_APP_URL** configured. 

After run => okta-aws test sts get-caller-identity and entered username and password, I got following error
**NOTE: Same configure setting works on Windows 10 machine and Mac**
```
Exception in thread "main" java.net.UnknownHostException: https: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at com.okta.tools.authentication.OktaAuthnClientImpl.primaryAuthentication(OktaAuthnClientImpl.java:54)
        at com.okta.tools.authentication.OktaAuthentication.getPrimaryAuthResponse(OktaAuthentication.java:128)
        at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:52)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:49)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
        at com.okta.tools.WithOkta.main(WithOkta.java:28)
```

![7a0f852e2e532e0c75394a3bb951022](https://user-images.githubusercontent.com/2981926/54961608-abb6ae00-4f1e-11e9-8897-bbf8228b3421.png)

Thanks for any help

**Comment by AlainODea** [comment]
OKTA_ORG cannot be a URL, it needs to be a domain name like example.okta.com.
