### ISSUE TITLE
Java 11 graphics error when setting OKTA_BROWSER_AUTH=true on Windows 10

### ISSUE THREAD

**Issue by hecsalazar** [oktadeveloper/okta-aws-cli-assume-role#288]
**Describe the bug**
Trying to run okta with the browser authentication enabled gives a JavaX graphic renderer error

**To Reproduce**
PS D:\> okta-aws
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)

Installed JavaFX 11 as instructed here in the "Runtime Images" section:
https://openjfx.io/openjfx-docs/#install-javafx

Current environment variables:
PS D:\> write-host $env:JAVA_HOME
C:\Program Files\Java\jdk-11.0.2
PS D:\> write-host $env:PATH_TO_FX_MODS
C:\Program Files\Java\javafx-jmods-11.0.2

**Expected behavior**
Should display browser authentication

**Screenshots**

**Comment by hecsalazar** [comment]
Did additional test to validate JavaFX installation with the HelloFX java sample:
PS D:\git\javafx_samples\HelloFX\CLI\hellofx> javac --module-path $env:PATH_TO_FX --add-modules javafx.controls HelloFX.java
java --module-path $env:PATH_TO_FX --add-modules javafx.controls HelloFX
![java_fx_test_2019-05-28_15-02-46](https://user-images.githubusercontent.com/10752909/58504928-b9c0bf00-8159-11e9-830f-56fb29216c12.png)

**Comment by hecsalazar** [comment]
Created PR to fix this and other problems:
https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/303

**Comment by mnatalonicb** [comment]
Hi @hecsalazar,

I am experiencing the same issue documented above, has there been a fix provided for this?

I am running JDK 11.0.6 and javafx 11.02.
