### ISSUE TITLE
OpenJDK 8 not supported, but OracleJDK 8 is?

### ISSUE THREAD

**Issue by wulftone** [oktadeveloper/okta-aws-cli-assume-role#300]
When I use
```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```
I get
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:41)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:130)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:100)
	at com.okta.tools.WithOkta.main(WithOkta.java:28)
```
And when I use
```
java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```
it works fine.  Is this expected?

**Comment by hecsalazar** [comment]
A PR was sent to fix with recent Java versions. I removed some dependencies on deprecated libraries in Java 8 PR: https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/303

**Comment by smithkb** [comment]
I'm still seeing this as an issue even after release 2.02 (containing PR #303 ). Running in Windows Powershell per the installation instructions.

java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/okta/tools/WithOkta has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by jmanning2k** [comment]
Release 2.0.2 (specifically, PR #303) seems to have set the minimum version to JDK 11. It breaks compatibility completely with 1.8.
https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/master/pom.xml#L184

Please revert the source and target versions to 1.8.  

I understand the desire to test and confirm it works with JDK 9 and 11, but I don't think you meant to set the minimum JDK version and drop JDK 1.8 support in a patch release.

**Comment by hecsalazar** [comment]
Part of fixes to make the tool usable. It was using api's from sun that are
not anymore available due licensing issues and they were removed from SDK 9
and later.

I would check with the maintainers if they want to create a Java 1.8
support branch.

1.8 is a dead-end, it's a 5-year old framework and java releases now have
shorter time span.

**Comment by kherrera-ebsco** [comment]
@hecsalazar I agree that we need to move on at some point, but unfortunately there are legacy issues preventing many from doing so. For me personally, this wouldn't be an issue if I could specify which version to install when using the `install.sh` script.

**Comment by hecsalazar** [comment]
What you propose is to have 2 versions of the tools.
I would consult the main maintainers if that's the call to keep another
legacy release branch or make a fork to try to make it work for your
use-case.
Unfortunately JDK has breaking changes after version 8, like JavaFX and Sun
libraries being taken out of the framework.
Consider JDK 8 is being sunset by Oracle by next year:
https://www.oracle.com/technetwork/java/java-se-support-roadmap.html

**Comment by kherrera-ebsco** [comment]
The ask is to be able to specify a released version when installing (`.../install.sh v1.0.10` or `.../install.sh v2.0.2`). This should not require continued maintenance of older versions, it would only require changes to the following files:

- [`install.sh`](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/43d54af3588380ffdd104be39257b087ebf33aba/bin/install.sh#L84)
- [`Install-OktaAwsCli.ps1`](https://github.com/oktadeveloper/okta-aws-cli-assume-role/blob/43d54af3588380ffdd104be39257b087ebf33aba/bin/Install-OktaAwsCli.ps1#L33)

This approach would allow users to stick to a known working version while maintainers make backwards incompatible releases.

**Comment by mraible** [comment]
Note: there are no maintainers of this project. I just blindly merge and release when I’m asked to do so.

**Comment by hecsalazar** [comment]
Thinking about this,

One way to do it without complexity can be to put a releases page that
points to release packages that contains a version of the install script
that allows to install that release.
I noticed that the released jar files are already available, there's just
to easy way to get to them.

This way if the install script has breaking changes, it will work within
it's own release version of script+jar file and no need to care for
backwards compatibility.

It's a common approach in major open source projects, here's an example:
https://github.com/istio/istio/releases/

I'd suggest to start with one of the last stable versions for JDK8 since
the latest was practically unusable

What are your thoughts?


Hector

**Comment by 8carlosf** [comment]
```
PREFIX=~/.okta releaseTag="v2.0.0" bash <(curl -fsSL https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/53bb97/bin/install.sh | grep -v "^releaseTag") -i
```
my _hacky_ way of installing a specific version

**Comment by maksimluzik** [comment]
Having same issue as well, also installing release tag 2.0.0 did not help like 8carlosf pointed out

**Comment by AshwinNS** [comment]
This will help in using different java versions as well.

https://dzone.com/articles/installing-openjdk-11-on-macos
