### ISSUE TITLE
bash: okta-aws: command not found

### ISSUE THREAD

**Issue by jepsenwan** [oktadeveloper/okta-aws-cli-assume-role#313]
**Describe the bug**
Can not run the command with the command output:
bash: okta-aws: command not found

**To Reproduce**
1. Run a centos 7 container.
2. Install the app:
PREFIX=~/.okta bash <(curl -fsSL https://raw.githubusercontent.com/oktadeveloper/okta-aws-cli-assume-role/master/bin/install.sh) -i
3. Export PATH=$PATH:$HOME/.okta/bin/
4. Run command okta-aws:
bash: okta-aws: command not found

no command found as well:
[root@4f30d23aeea9 .okta]# find / -name okta-aws
[root@4f30d23aeea9 .okta]# 

[root@4f30d23aeea9 .okta]# tree
.
|-- bash_functions
|-- bin
|   |-- awscli
|   |-- okta-credential_process
|   |-- okta-listroles
|   `-- withokta
|-- config.properties
|-- fish_functions
|   |-- okta-aws.fish
|   `-- okta-sls.fish
|-- logging.properties
|-- okta-aws-cli-2.0.2.jar
|-- okta-aws-cli.jar -> okta-aws-cli-2.0.2.jar
`-- profiles

2 directories, 12 files

** Expected behavior **

[root@4f30d23aeea9 .okta]# tree
.
|-- bash_functions
|-- bin
|   |-- awscli
|   |-- okta-credential_process
|   |-- okta-listroles
|   `-- withokta
|-- config.properties
|-- fish_functions
|   |-- okta-aws.fish
|   `-- okta-sls.fish
|-- logging.properties
|-- okta-aws-cli-2.0.2.jar
|-- okta-aws-cli.jar -> okta-aws-cli-2.0.2.jar
`-- profiles

**Screenshots**

**Additional context**

**Comment by amir-hadi** [comment]
You need to `source` the `bash_functions` in `~/.okta`

**Comment by jepsenwan** [comment]
@amir-hadi  Thanks. It does have this function, but I encountered the below error when running it:
okta-aws test sts get-caller-identity
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:243)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)

root@732dd6913da9:~/.okta# java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu114.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu114.04ppa1, mixed mode, sharing)

Please tell me if any further information required. 

Thanks.

**Comment by cmouser** [comment]
I'm getting the same error with JDK 11 and OpenJDK 12 on Windows 10.

**Comment by jchan172** [comment]
I'm getting the same error with JDK 11 and OpenJDK 12 on Linux (Manjaro). I've also installed JavaFX, but that didn't help.

**Comment by shashijais789** [comment]
I have sourced the bash files. Not running the command:  okta-aws test sts get-caller-identity
I am getting below:
Error: Could not find or load main class com.okta.tools.WithOkta

**Comment by JohnMealy23** [comment]
I'm experiencing the same error:

> Error: Could not find or load main class com.okta.tools.WithOkta

I've attempted while running `java version "1.8.0_221"` and `java version "12.0.2"`.  Not sure what else to attempt.  Help would be appreciated!

**Comment by DominicTobias-b1** [comment]
Same issue after running

```
brew install python
pip3 install okta-awscli
```

Gets installed here `~/Library/Python/3.7/bin`, add that to my path but it's not found

**Comment by vennemp** [comment]
I ran source bash_functions but not when I run the okta-aws command it says "withokta: command not found"

**Comment by devops-expanse** [comment]
why are we dealing with java here?

**Comment by utsavcoding** [comment]
Try uninstalling the okta-awscli & then install it using sudo. `sudo pip3 install okta-awscli`

**Comment by tatianajiselle** [comment]
my issue was that i needed to add the `.okta/bin` to the path variable in my `.zshrc` -- hope this can help someone (:

**Comment by jonrosenskispark** [comment]
running into this issue. source .bash_functions does not help. Made sure .okta/bin is in $PATH. still getting okta-aws: command not found . Any ideas?
