### ISSUE TITLE
Unable to get past login

### ISSUE THREAD

**Issue by NickKarsky** [oktadeveloper/okta-aws-cli-assume-role#314]
I'm using a local VM running LinuxMint Cinnamon 19.
`java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
`
When trying to do any command, after asking for my user and pass, I get this Exception:
`Exception in thread "main" com.okta.tools.saml.OktaSaml$PromptForFactorException: Unsupported App sign on rule: 'Prompt for factor'. 
Please contact your administrator.
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsFromDocument(OktaSaml.java:69)
	at com.okta.tools.saml.OktaSaml.getSamlResponseForAws(OktaSaml.java:55)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:48)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:30)
`

I got the same error before and after setting multi-factor authentication.

**Comment by alfredocambera** [comment]
I had this same issue and it was because I had cleared the `~/.okta/config.properties` file. I moved the `~/.okta` dir to a backup directory, reinstalled and everything started working again.
