### ISSUE TITLE
Java exception in 2.0.0 and later with MFA Push

### ISSUE THREAD

**Issue by jimlawton** [oktadeveloper/okta-aws-cli-assume-role#316]
**Describe the bug**
If I try to do `OKTA_PROFILE=default awscli sts get-caller-identity` with 2.0.0 or later, it prompts for user/pass and MFA, but then fails immediately with a Java exception.

**To Reproduce**
1. Install Okta AWS CLI 2.0.0 or later (verified with 2.0.0 and 2.0.2).
2. `$ OKTA_PROFILE=default awscli sts get-caller-identity`
3. Enter username, password.
4. On prompt for MFA, select `[ 1 ] : Okta Verify (Push)`
5. See error.

**Expected behavior**
In 1.0.10 and earlier, it waits for MFA verification and then prints credentials.

**Screenshots**
```
> OKTA_PROFILE=default awscli sts get-caller-identity
Username: xxxxxxxxxx
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Okta Verify (Push)
[ 2 ] : Okta Verify (TOTP)
Selection: 1

Push Factor Authentication
Exception in thread "main" org.json.JSONException: JSONObject["poll"] not found.
	at org.json.JSONObject.get(JSONObject.java:566)
	at org.json.JSONObject.getJSONObject(JSONObject.java:778)
	at com.okta.tools.authentication.OktaMFA.handlePushPolling(OktaMFA.java:293)
	at com.okta.tools.authentication.OktaMFA.verifyAnswer(OktaMFA.java:285)
	at com.okta.tools.authentication.OktaMFA.pushFactor(OktaMFA.java:242)
	at com.okta.tools.authentication.OktaMFA.getSessionToken(OktaMFA.java:103)
	at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:64)
	at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:87)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:30)
>
```
**Additional context**
The MFA push is issued, and I get a prompt on my phone to approve.

`config.properties`:
```
#OktaAWSCLI
OKTA_ORG=xxxxxxxxxx
OKTA_AWS_APP_URL=https://xxxxxxxxxx
OKTA_BROWSER_AUTH=false
OKTA_STS_DURATION=43200
OKTA_USERNAME=xxxxxxxxxx
OKTA_MFA_CHOICE=Okta.push
```

**Comment by cdebergh** [comment]
I am getting this with Okta.sms as well in 2.0. I try the docker version (1.0.3) and it works.
