### ISSUE TITLE
Which version for alpine-linux 3.9?

### ISSUE THREAD

**Issue by Jaff** [oktadeveloper/okta-aws-cli-assume-role#327]
I'm running cloudposse/atlantis container and when I try to install okta-aws-cli it complains: 
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/okta/tools/ListRoles has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by jeremyplichtafc** [comment]
Starting with version 2.0 of this tool it has been compiled with Java 11 since there were new features added in that depend on it. If you download [latest v1 release jar](https://github.com/oktadeveloper/okta-aws-cli-assume-role/releases/download/v1.0.10/okta-aws-cli-1.0.10.jar) and put it in `~/.okta/okta-aws-cli.jar` it should work with Java8. There have been discussions of modifying the `install.sh` script to specify the release you want to install but that has not been done yet

**Comment by Jaff** [comment]
Thanks, good to know. Alternatively, I added jdk11 but getting same results as with okta-aws-cli-2.0.3.jar:
```
bash-4.4# ln -s okta-aws-cli-1.0.10.jar  okta-aws-cli.jar
bash-4.4# ./bin/okta-listroles 
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
bash-4.4# java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.4+11-alpine-r0, mixed mode)

```

**Comment by Jaff** [comment]
@jeremyplichtafc I tried switching back to openjdk8, and using 1.0.10.jar, with previous results:
```
bash-4.4# okta-listroles 
Exception in thread "main" java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:41)
	at com.okta.tools.ListRoles.main(ListRoles.java:43)
bash-4.4# ls -la /root/.okta/
total 109100
drwxr-xr-x    1 root     root          4096 Aug  5 22:42 .
drwx------    1 root     root          4096 Aug  5 22:56 ..
-rw-r--r--    1 root     root           128 Aug  5 22:42 bash_functions
drwxr-xr-x    2 root     root          4096 Aug  5 22:42 bin
-rw-r--r--    1 root     root           153 Aug  5 22:42 config.properties
drwxr-xr-x    2 root     root          4096 Aug  5 22:42 fish_functions
-rw-r--r--    1 root     root            68 Aug  5 22:42 logging.properties
-rw-r--r--    1 root     root      54458008 Aug  5 22:42 okta-aws-cli-1.0.10.jar
-rw-r--r--    1 root     root      57224504 Aug  5 22:42 okta-aws-cli-2.0.3.jar
lrwxrwxrwx    1 root     root            23 Aug  5 22:42 okta-aws-cli.jar -> okta-aws-cli-1.0.10.jar
bash-4.4# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

```

**Comment by Jaff** [comment]
I'm having a strong suspicion that there is an implicit dependency on gtk libs, implying the presentation of a user-input dialog. Am I correct?

**Comment by Jaff** [comment]
I ran `jdeps` against the okta-aws-cli-2.0.3.jar and came up with this set of 'not found' dependencies: (ran grep -n 'not found' on the output of jdeps)
```
$ grep -n 'not found' ../../okta-aws-cli.jdeps 
16:okta-aws-cli.jar -> not found
690:   com.amazonaws.util                                 -> javax.xml.bind                                     not found
831:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar                                not found
832:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar.trex                           not found
833:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar.xmlschema                      not found
834:   com.ctc.wstx.msv                                   -> com.sun.msv.reader                                 not found
835:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.trex.ng                         not found
836:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.util                            not found
837:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.xmlschema                       not found
838:   com.ctc.wstx.msv                                   -> com.sun.msv.util                                   not found
839:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier                               not found
840:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier.regexp                        not found
841:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier.regexp.xmlschema              not found
861:   com.ctc.wstx.osgi                                  -> org.osgi.framework                                 not found
1377:   com.google.common.base                             -> com.google.errorprone.annotations.concurrent       not found
1413:   com.google.common.collect                          -> com.google.errorprone.annotations.concurrent       not found
1445:   com.google.common.graph                            -> com.google.errorprone.annotations.concurrent       not found
1488:   com.google.common.math                             -> com.google.errorprone.annotations.concurrent       not found
1501:   com.google.common.net                              -> com.google.errorprone.annotations.concurrent       not found
4184:   net.shibboleth.utilities.java.support.httpclient   -> org.apache.http.client.cache                       not found
4194:   net.shibboleth.utilities.java.support.httpclient   -> org.apache.http.impl.client.cache                  not found
4220:   net.shibboleth.utilities.java.support.net          -> javax.servlet                                      not found
4221:   net.shibboleth.utilities.java.support.net          -> javax.servlet.http                                 not found
4264:   net.shibboleth.utilities.java.support.security     -> com.beust.jcommander                               not found
4265:   net.shibboleth.utilities.java.support.security     -> com.beust.jcommander.converters                    not found
4280:   net.shibboleth.utilities.java.support.security     -> javax.servlet                                      not found
4294:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.cert                              not found
4295:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.cert.jcajce                       not found
4300:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.openssl.jcajce                    not found
4301:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.operator                          not found
4302:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.operator.jcajce                   not found
4525:   org.apache.commons.configuration2                  -> org.yaml.snakeyaml                                 not found
4530:   org.apache.commons.configuration2.beanutils        -> org.apache.commons.beanutils                       not found
4566:   org.apache.commons.configuration2.builder.combined -> org.apache.commons.beanutils                       not found
4612:   org.apache.commons.configuration2.interpol         -> org.apache.commons.jexl2                           not found
4632:   org.apache.commons.configuration2.io               -> org.apache.commons.vfs2                            not found
4633:   org.apache.commons.configuration2.io               -> org.apache.commons.vfs2.provider                   not found
4659:   org.apache.commons.configuration2.reloading        -> org.apache.commons.vfs2                            not found
4667:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver                            not found
4668:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.helpers                    not found
4669:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.readers                    not found
4670:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.tools                      not found
4678:   org.apache.commons.configuration2.spring           -> org.springframework.beans.factory                  not found
4679:   org.apache.commons.configuration2.spring           -> org.springframework.core.env                       not found
4680:   org.apache.commons.configuration2.spring           -> org.springframework.core.io                        not found
4681:   org.apache.commons.configuration2.spring           -> org.springframework.util                           not found
4695:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath                          not found
4696:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri                       not found
4697:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri.compiler              not found
4698:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri.model                 not found
4703:   org.apache.commons.configuration2.web              -> javax.servlet                                      not found
4855:   org.apache.commons.logging.impl                    -> javax.servlet                                      not found
4856:   org.apache.commons.logging.impl                    -> org.apache.avalon.framework.logger                 not found
4858:   org.apache.commons.logging.impl                    -> org.apache.log                                     not found
4859:   org.apache.commons.logging.impl                    -> org.apache.log4j                                   not found
5434:   org.apache.velocity.anakia                         -> com.werken.xpath                                   not found
5439:   org.apache.velocity.anakia                         -> org.apache.tools.ant                               not found
5440:   org.apache.velocity.anakia                         -> org.apache.tools.ant.taskdefs                      not found
5445:   org.apache.velocity.anakia                         -> org.jdom                                           not found
5446:   org.apache.velocity.anakia                         -> org.jdom.input                                     not found
5447:   org.apache.velocity.anakia                         -> org.jdom.output                                    not found
5471:   org.apache.velocity.app.event.implement            -> org.apache.oro.text.perl                           not found
5497:   org.apache.velocity.convert                        -> org.apache.oro.text.perl                           not found
5498:   org.apache.velocity.convert                        -> org.apache.tools.ant                               not found
5547:   org.apache.velocity.runtime.log                    -> javax.servlet                                      not found
5550:   org.apache.velocity.runtime.log                    -> org.apache.log                                     not found
5551:   org.apache.velocity.runtime.log                    -> org.apache.log.format                              not found
5552:   org.apache.velocity.runtime.log                    -> org.apache.log.output.io                           not found
5553:   org.apache.velocity.runtime.log                    -> org.apache.log4j                                   not found
5627:   org.apache.velocity.servlet                        -> javax.servlet                                      not found
5628:   org.apache.velocity.servlet                        -> javax.servlet.http                                 not found
5647:   org.apache.velocity.texen.ant                      -> org.apache.tools.ant                               not found
5717:   org.apache.xml.security.binding.excc14n            -> javax.xml.bind                                     not found
5718:   org.apache.xml.security.binding.excc14n            -> javax.xml.bind.annotation                          not found
5723:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind                                     not found
5724:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind.annotation                          not found
5725:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind.annotation.adapters                 not found
5729:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind                                     not found
5730:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind.annotation                          not found
5731:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind.annotation.adapters                 not found
5736:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind                                     not found
5737:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind.annotation                          not found
5738:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind.annotation.adapters                 not found
5744:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind                                     not found
5745:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind.annotation                          not found
5746:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind.annotation.adapters                 not found
5781:   org.apache.xml.security.configuration              -> javax.xml.bind                                     not found
5782:   org.apache.xml.security.configuration              -> javax.xml.bind.annotation                          not found
5955:   org.apache.xml.security.stax.config                -> javax.xml.bind                                     not found
5984:   org.apache.xml.security.stax.ext                   -> javax.xml.bind                                     not found
6053:   org.apache.xml.security.stax.impl.processor.input  -> javax.xml.bind                                     not found
6213:   org.apache.xml.security.transforms.implementations -> org.apache.xml.dtm                                 not found
6221:   org.apache.xml.security.transforms.implementations -> org.apache.xpath                                   not found
6222:   org.apache.xml.security.transforms.implementations -> org.apache.xpath.functions                         not found
6223:   org.apache.xml.security.transforms.implementations -> org.apache.xpath.objects                           not found
6254:   org.apache.xml.security.utils                      -> org.apache.xml.utils                               not found
6255:   org.apache.xml.security.utils                      -> org.apache.xpath                                   not found
6256:   org.apache.xml.security.utils                      -> org.apache.xpath.compiler                          not found
6257:   org.apache.xml.security.utils                      -> org.apache.xpath.objects                           not found
8162:   org.joda.time                                      -> org.joda.convert                                   not found
8172:   org.joda.time.base                                 -> org.joda.convert                                   not found
8490:   org.opensaml.messaging.decoder.servlet             -> javax.servlet.http                                 not found
8521:   org.opensaml.messaging.encoder.servlet             -> javax.servlet.http                                 not found
8537:   org.opensaml.messaging.error.servlet               -> javax.servlet.http                                 not found
8579:   org.opensaml.profile.action                        -> javax.servlet.http                                 not found
8614:   org.opensaml.profile.logic                         -> javax.servlet                                      not found
8615:   org.opensaml.profile.logic                         -> javax.servlet.http                                 not found
8654:   org.opensaml.saml.common.binding                   -> javax.servlet.http                                 not found
8751:   org.opensaml.saml.common.binding.security.impl     -> javax.servlet.http                                 not found
9426:   org.opensaml.saml.saml1.binding.decoding.impl      -> javax.servlet.http                                 not found
9450:   org.opensaml.saml.saml1.binding.encoding.impl      -> javax.servlet                                      not found
9451:   org.opensaml.saml.saml1.binding.encoding.impl      -> javax.servlet.http                                 not found
9626:   org.opensaml.saml.saml2.binding.decoding.impl      -> javax.servlet.http                                 not found
9671:   org.opensaml.saml.saml2.binding.encoding.impl      -> javax.servlet                                      not found
9672:   org.opensaml.saml.saml2.binding.encoding.impl      -> javax.servlet.http                                 not found
9738:   org.opensaml.saml.saml2.binding.security.impl      -> javax.servlet.http                                 not found
9921:   org.opensaml.saml.saml2.profile.impl               -> javax.servlet.http                                 not found
9973:   org.opensaml.saml.saml2.wssecurity.messaging.impl  -> javax.servlet                                      not found
9974:   org.opensaml.saml.saml2.wssecurity.messaging.impl  -> javax.servlet.http                                 not found
10188:   org.opensaml.security.messaging                    -> javax.servlet                                      not found
10202:   org.opensaml.security.messaging.impl               -> javax.servlet                                      not found
10203:   org.opensaml.security.messaging.impl               -> javax.servlet.http                                 not found
10474:   org.opensaml.soap.soap11.decoder.http.impl         -> javax.servlet                                      not found
10475:   org.opensaml.soap.soap11.decoder.http.impl         -> javax.servlet.http                                 not found
10490:   org.opensaml.soap.soap11.encoder.http.impl         -> javax.servlet                                      not found
10491:   org.opensaml.soap.soap11.encoder.http.impl         -> javax.servlet.http                                 not found
```

**Comment by Jaff** [comment]
Same process as previous post, using 2.0.3 jar; details:
```
bash-4.4# java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.4+11-alpine-r0, mixed mode)
bash-4.4# /usr/lib/jvm/default-jvm/jre/bin/jdeps /root/.okta/okta-aws-cli-2.0.3.jar > /home/atlantis/okta-aws-cli-2.0.3.jdeps
bash-4.4# cd /home/atlantis/
bash-4.4# grep -n 'not found' okta-aws-cli-2.0.3.jdeps 
16:okta-aws-cli-2.0.3.jar -> not found
690:   com.amazonaws.util                                 -> javax.xml.bind                                     not found
831:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar                                not found
832:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar.trex                           not found
833:   com.ctc.wstx.msv                                   -> com.sun.msv.grammar.xmlschema                      not found
834:   com.ctc.wstx.msv                                   -> com.sun.msv.reader                                 not found
835:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.trex.ng                         not found
836:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.util                            not found
837:   com.ctc.wstx.msv                                   -> com.sun.msv.reader.xmlschema                       not found
838:   com.ctc.wstx.msv                                   -> com.sun.msv.util                                   not found
839:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier                               not found
840:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier.regexp                        not found
841:   com.ctc.wstx.msv                                   -> com.sun.msv.verifier.regexp.xmlschema              not found
861:   com.ctc.wstx.osgi                                  -> org.osgi.framework                                 not found
1377:   com.google.common.base                             -> com.google.errorprone.annotations.concurrent       not found
1413:   com.google.common.collect                          -> com.google.errorprone.annotations.concurrent       not found
1445:   com.google.common.graph                            -> com.google.errorprone.annotations.concurrent       not found
1488:   com.google.common.math                             -> com.google.errorprone.annotations.concurrent       not found
1501:   com.google.common.net                              -> com.google.errorprone.annotations.concurrent       not found
4184:   net.shibboleth.utilities.java.support.httpclient   -> org.apache.http.client.cache                       not found
4194:   net.shibboleth.utilities.java.support.httpclient   -> org.apache.http.impl.client.cache                  not found
4220:   net.shibboleth.utilities.java.support.net          -> javax.servlet                                      not found
4221:   net.shibboleth.utilities.java.support.net          -> javax.servlet.http                                 not found
4264:   net.shibboleth.utilities.java.support.security     -> com.beust.jcommander                               not found
4265:   net.shibboleth.utilities.java.support.security     -> com.beust.jcommander.converters                    not found
4280:   net.shibboleth.utilities.java.support.security     -> javax.servlet                                      not found
4294:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.cert                              not found
4295:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.cert.jcajce                       not found
4300:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.openssl.jcajce                    not found
4301:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.operator                          not found
4302:   net.shibboleth.utilities.java.support.security     -> org.bouncycastle.operator.jcajce                   not found
4525:   org.apache.commons.configuration2                  -> org.yaml.snakeyaml                                 not found
4530:   org.apache.commons.configuration2.beanutils        -> org.apache.commons.beanutils                       not found
4566:   org.apache.commons.configuration2.builder.combined -> org.apache.commons.beanutils                       not found
4612:   org.apache.commons.configuration2.interpol         -> org.apache.commons.jexl2                           not found
4632:   org.apache.commons.configuration2.io               -> org.apache.commons.vfs2                            not found
4633:   org.apache.commons.configuration2.io               -> org.apache.commons.vfs2.provider                   not found
4659:   org.apache.commons.configuration2.reloading        -> org.apache.commons.vfs2                            not found
4667:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver                            not found
4668:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.helpers                    not found
4669:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.readers                    not found
4670:   org.apache.commons.configuration2.resolver         -> org.apache.xml.resolver.tools                      not found
4678:   org.apache.commons.configuration2.spring           -> org.springframework.beans.factory                  not found
4679:   org.apache.commons.configuration2.spring           -> org.springframework.core.env                       not found
4680:   org.apache.commons.configuration2.spring           -> org.springframework.core.io                        not found
4681:   org.apache.commons.configuration2.spring           -> org.springframework.util                           not found
4695:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath                          not found
4696:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri                       not found
4697:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri.compiler              not found
4698:   org.apache.commons.configuration2.tree.xpath       -> org.apache.commons.jxpath.ri.model                 not found
4703:   org.apache.commons.configuration2.web              -> javax.servlet                                      not found
4855:   org.apache.commons.logging.impl                    -> javax.servlet                                      not found
4856:   org.apache.commons.logging.impl                    -> org.apache.avalon.framework.logger                 not found
4858:   org.apache.commons.logging.impl                    -> org.apache.log                                     not found
4859:   org.apache.commons.logging.impl                    -> org.apache.log4j                                   not found
5434:   org.apache.velocity.anakia                         -> com.werken.xpath                                   not found
5439:   org.apache.velocity.anakia                         -> org.apache.tools.ant                               not found
5440:   org.apache.velocity.anakia                         -> org.apache.tools.ant.taskdefs                      not found
5445:   org.apache.velocity.anakia                         -> org.jdom                                           not found
5446:   org.apache.velocity.anakia                         -> org.jdom.input                                     not found
5447:   org.apache.velocity.anakia                         -> org.jdom.output                                    not found
5471:   org.apache.velocity.app.event.implement            -> org.apache.oro.text.perl                           not found
5497:   org.apache.velocity.convert                        -> org.apache.oro.text.perl                           not found
5498:   org.apache.velocity.convert                        -> org.apache.tools.ant                               not found
5547:   org.apache.velocity.runtime.log                    -> javax.servlet                                      not found
5550:   org.apache.velocity.runtime.log                    -> org.apache.log                                     not found
5551:   org.apache.velocity.runtime.log                    -> org.apache.log.format                              not found
5552:   org.apache.velocity.runtime.log                    -> org.apache.log.output.io                           not found
5553:   org.apache.velocity.runtime.log                    -> org.apache.log4j                                   not found
5627:   org.apache.velocity.servlet                        -> javax.servlet                                      not found
5628:   org.apache.velocity.servlet                        -> javax.servlet.http                                 not found
5647:   org.apache.velocity.texen.ant                      -> org.apache.tools.ant                               not found
5717:   org.apache.xml.security.binding.excc14n            -> javax.xml.bind                                     not found
5718:   org.apache.xml.security.binding.excc14n            -> javax.xml.bind.annotation                          not found
5723:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind                                     not found
5724:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind.annotation                          not found
5725:   org.apache.xml.security.binding.xmldsig            -> javax.xml.bind.annotation.adapters                 not found
5729:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind                                     not found
5730:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind.annotation                          not found
5731:   org.apache.xml.security.binding.xmldsig11          -> javax.xml.bind.annotation.adapters                 not found
5736:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind                                     not found
5737:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind.annotation                          not found
5738:   org.apache.xml.security.binding.xmlenc             -> javax.xml.bind.annotation.adapters                 not found
5744:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind                                     not found
5745:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind.annotation                          not found
5746:   org.apache.xml.security.binding.xmlenc11           -> javax.xml.bind.annotation.adapters                 not found
5781:   org.apache.xml.security.configuration              -> javax.xml.bind                                     not found
5782:   org.apache.xml.security.configuration              -> javax.xml.bind.annotation                          not found
5955:   org.apache.xml.security.stax.config                -> javax.xml.bind                                     not found
5984:   org.apache.xml.security.stax.ext                   -> javax.xml.bind                                     not found
6053:   org.apache.xml.security.stax.impl.processor.input  -> javax.xml.bind                                     not found
6213:   org.apache.xml.security.transforms.implementations -> org.apache.xml.dtm                                 not found
6221:   org.apache.xml.security.transforms.implementations -> org.apache.xpath                                   not found
6222:   org.apache.xml.security.transforms.implementations -> org.apache.xpath.functions                         not found
6223:   org.apache.xml.security.transforms.implementations -> org.apache.xpath.objects                           not found
6254:   org.apache.xml.security.utils                      -> org.apache.xml.utils                               not found
6255:   org.apache.xml.security.utils                      -> org.apache.xpath                                   not found
6256:   org.apache.xml.security.utils                      -> org.apache.xpath.compiler                          not found
6257:   org.apache.xml.security.utils                      -> org.apache.xpath.objects                           not found
8162:   org.joda.time                                      -> org.joda.convert                                   not found
8172:   org.joda.time.base                                 -> org.joda.convert                                   not found
8490:   org.opensaml.messaging.decoder.servlet             -> javax.servlet.http                                 not found
8521:   org.opensaml.messaging.encoder.servlet             -> javax.servlet.http                                 not found
8537:   org.opensaml.messaging.error.servlet               -> javax.servlet.http                                 not found
8579:   org.opensaml.profile.action                        -> javax.servlet.http                                 not found
8614:   org.opensaml.profile.logic                         -> javax.servlet                                      not found
8615:   org.opensaml.profile.logic                         -> javax.servlet.http                                 not found
8654:   org.opensaml.saml.common.binding                   -> javax.servlet.http                                 not found
8751:   org.opensaml.saml.common.binding.security.impl     -> javax.servlet.http                                 not found
9426:   org.opensaml.saml.saml1.binding.decoding.impl      -> javax.servlet.http                                 not found
9450:   org.opensaml.saml.saml1.binding.encoding.impl      -> javax.servlet                                      not found
9451:   org.opensaml.saml.saml1.binding.encoding.impl      -> javax.servlet.http                                 not found
9626:   org.opensaml.saml.saml2.binding.decoding.impl      -> javax.servlet.http                                 not found
9671:   org.opensaml.saml.saml2.binding.encoding.impl      -> javax.servlet                                      not found
9672:   org.opensaml.saml.saml2.binding.encoding.impl      -> javax.servlet.http                                 not found
9738:   org.opensaml.saml.saml2.binding.security.impl      -> javax.servlet.http                                 not found
9921:   org.opensaml.saml.saml2.profile.impl               -> javax.servlet.http                                 not found
9973:   org.opensaml.saml.saml2.wssecurity.messaging.impl  -> javax.servlet                                      not found
9974:   org.opensaml.saml.saml2.wssecurity.messaging.impl  -> javax.servlet.http                                 not found
10188:   org.opensaml.security.messaging                    -> javax.servlet                                      not found
10202:   org.opensaml.security.messaging.impl               -> javax.servlet                                      not found
10203:   org.opensaml.security.messaging.impl               -> javax.servlet.http                                 not found
10474:   org.opensaml.soap.soap11.decoder.http.impl         -> javax.servlet                                      not found
10475:   org.opensaml.soap.soap11.decoder.http.impl         -> javax.servlet.http                                 not found
10490:   org.opensaml.soap.soap11.encoder.http.impl         -> javax.servlet                                      not found
10491:   org.opensaml.soap.soap11.encoder.http.impl         -> javax.servlet.http                                 not found
bash-4.4# 
```

**Comment by jeremyplichtafc** [comment]
It does require javafx, which on linux also needs gtk and a window manager installed. This is for the  browser authentication capability (if you are using a authentication provider for okta like Google). Are you using browser authentication or just CLI authentication? We could look into finding ways to get this tool compiled without javafx for people not needing browser authentication, or using an alternate browser auth tool like webdriver

**Comment by Jaff** [comment]
This is intended to be run without user interaction, as a part of infrastructure automation tool (https://github.com/runatlantis/atlantis)

---
Mark Jaffe
jaffe.mark@gmail.com
(408) 807-2093
@Jaff
http://markie.info

**Comment by jeremyplichtafc** [comment]
Cool project. Guess I don't fully understand your use case. Why would you not just use an AWS instance role for this though?
