### ISSUE TITLE
SMS MFA option is broken in v2.0.4 release

### ISSUE THREAD

**Issue by tmann-fuze** [oktadeveloper/okta-aws-cli-assume-role#349]
I updated to v2.0.4 and while MFA Push was fixed, SMS still doesn't work for me.

```
----snippet----
# okta-aws lab sts get-caller-identity
Username: myusername
Password:

Multi-Factor authentication is required. Please select a factor to use.
Factors:
[ 1 ] : Okta Verify (Push)
[ 2 ] : SMS Verification
[ 3 ] : Google Authenticator
[ 4 ] : Okta Verify (TOTP)
Selection: 2
SMS Factor Authentication
Enter 'change factor' to use a different factor
Exception in thread "main" org.json.JSONException: JSONObject["sessionToken"] not found.
    at org.json.JSONObject.get(JSONObject.java:566)
    at org.json.JSONObject.getString(JSONObject.java:851)
    at com.okta.tools.authentication.OktaMFA.verifyAnswer(OktaMFA.java:287)
    at com.okta.tools.authentication.OktaMFA.smsFactor(OktaMFA.java:166)
    at com.okta.tools.authentication.OktaMFA.getSessionToken(OktaMFA.java:97)
    at com.okta.tools.authentication.OktaMFA.promptForFactor(OktaMFA.java:64)
    at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:87)
    at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
    at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
    at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
    at com.okta.tools.WithOkta.main(WithOkta.java:30)```

**Comment by jeremyplichtafc** [comment]
I tried looking at the changes in https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/332/files and the original refactor https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/280 ... it looks like the original code checked if `sessionToken` was set in the json response and if it wasn't continued on to the push verification. I am not sure why `sessionToken` is not in the response coming back from you. I don't have access to a Okta account that is setup with Push or SMS verification (we delegate our Okta authentication to a different identity provider that uses a different MFA). If someone else is able to dig in further and submit a PR that would help
