### ISSUE TITLE
StringIndexOutOfBoundsException with java version

### ISSUE THREAD

**Issue by benjaminkomen** [oktadeveloper/okta-aws-cli-assume-role#358]
**Describe the bug**
When executing the following command, to refresh my AWS token, I get an exception:
`java -jar ~/.okta/okta-aws-cli-2.0.4.jar s3 ls`

**To Reproduce**
1. Execute `java -jar ~/.okta/okta-aws-cli-2.0.4.jar s3 ls`
2. You will get the following stacktrace:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.okta.tools.OktaAwsConfig.runProgram(OktaAwsConfig.java:90)
	at com.okta.tools.OktaAwsConfig.lambda$deferProgram$2(OktaAwsConfig.java:85)
	at com.okta.tools.authentication.OktaAuthentication.getPassword(OktaAuthentication.java:169)
	at com.okta.tools.authentication.OktaAuthentication.getPrimaryAuthResponse(OktaAuthentication.java:127)
	at com.okta.tools.authentication.OktaAuthentication.getOktaSessionToken(OktaAuthentication.java:51)
	at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:47)
	at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
	at com.okta.tools.WithOkta.main(WithOkta.java:30)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
	at org.apache.commons.lang.SystemUtils.<clinit>(SystemUtils.java:818)
	... 9 more
```
3. When executing `java --version`, you will see:
```
openjdk 14 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```
So this might be related to the length of the version number?
4. However, when doing `jenv versions`, I get the following:
```
system
  1.8
  1.8.0.242
  11.0
  11.0.2
  13.0
  13.0.1
* 14 (set by /Users/MY_USER_NAME/.jenv/version)
  openjdk64-1.8.0.242
  openjdk64-13.0.1
  openjdk64-14
  oracle64-11.0.2
```
So here the version seems to be 2 characters long, like expected by the program.

**Expected behavior**
The ability to log in, without exceptions.

**Additional context**
n/a

**Comment by kpeters-cbsi** [comment]
This is happening for me on Java 19. Curiously, if I use v1.0.2 to log in first, I am then able to execute `okta-aws test sts get-caller-identity` successfully (`okta-aws-cli` v.3.0.0)
