### ISSUE TITLE
null pointer on v2.0.4

### ISSUE THREAD

**Issue by trinaryouroboros** [oktadeveloper/okta-aws-cli-assume-role#361]
Running a linux instance in AWS Cloud9, was able to use the tool before, but removing ~/.okta and reinstalling with latest version and setting up config.properties like before, I get the following null pointer exception:

SystemAdminAccessRole:~ $ awscli s3 ls
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.net.URI$Parser.parse(URI.java:3127)
        at java.base/java.net.URI.<init>(URI.java:623)
        at java.base/java.net.URI.create(URI.java:904)
        at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
        at com.okta.tools.saml.OktaAppClientImpl.launchApp(OktaAppClientImpl.java:40)
        at com.okta.tools.saml.OktaSaml.getSamlResponseForAwsRefresh(OktaSaml.java:59)
        at com.okta.tools.saml.OktaSaml.getSamlResponse(OktaSaml.java:45)
        at com.okta.tools.OktaAwsCliAssumeRole.doRequest(OktaAwsCliAssumeRole.java:132)
        at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:102)
        at com.okta.tools.WithOkta.main(WithOkta.java:30)

**Comment by trinaryouroboros** [comment]
This was reported in error, OKTA_AWS_APP_URL= was missing
