### ISSUE TITLE
Error when selecting Role to assume

### ISSUE THREAD

**Issue by jonjohnston** [oktadeveloper/okta-aws-cli-assume-role#39]
Okta implemented new method to console login to child accounts. This new method uses a fixed role: Okta-Idp-cross-account-role

I don;t believe the cli takes this into account. AWS credentials being used is from account 2222222222 which works because the cli uses the GetRole command. But fails when selecting 1234567890, possibly because it is running the GetRole command but the role is not in 2222222222 account and is not switching roles to the 1234567890 account via Okta-Idp-cross-account-role before doing the GetRole
sdk-1.11.165.jar com.okta.tools.awscli
Username: myuser
Password:

Please choose the role you would like to assume:
[ 1 ]: arn:aws:iam::1234567890:role/Testing1
[ 2 ]: arn:aws:iam::2222222222:role/Testing2
Selection: 1
13:46:27 [main] DEBUG com.okta.tools.awscli - Cross-account role is Testing1
13:46:28 [main] DEBUG com.okta.tools.awscli - Creating the AWS Identity Management client
13:46:28 [main] DEBUG com.okta.tools.awscli - Getting role: Testing1
Exception in thread "main" com.amazonaws.services.identitymanagement.model.NoSuchEntityException: Role not found for Testing1 (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 052303fa-7098-11e7-9234-1707482cd147)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:8275)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:8251)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.executeGetRole(AmazonIdentityManagementClient.java:4390)
        at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.getRole(AmazonIdentityManagementClient.java:4367)
        at com.okta.tools.awscli.GetRoleToAssume(awscli.java:437)
        at com.okta.tools.awscli.main(awscli.java:119)

**Comment by opragel** [comment]
I am experiencing the exact same issue. I can assume roles in the "master" account, but not roles in the other connected accounts, despite the fact that the connected account roles are displayed in the list of options.

@jonjohnston I contacted Okta support about this and this was the short version of their answer "Unfortunately this particular SDK is no longer supported, the reason it was also removed from our developers portal."

I think this is a solvable issue, but I'm not sure if anyone from Okta is still maintaining this repo.

**Comment by opragel** [comment]
I reread this. All the roles are intended to live under one account. https://support.okta.com/help/servlet/fileField?retURL=%2Fhelp%2Fapex%2FOktaArticleDetailPage%3FchildCateg%3D%26id%3DkA0F0000000McF7KAK%26source%3DDocumentation&entityId=ka02A000000XdHMQA0&_CONFIRMATIONTOKEN=VmpFPSxNakF4Tnkwd09DMHdPRlF3TnpvMU1Eb3lOUzQzTWpkYSxzWE90RzU1STI0aS1EOGxNemlWWnJjLFlqZ3hZemhp&common.udd.actions.ActionsUtilORIG_URI=%2Fhelp%2Fservlet%2FfileField&field=File_Attachment__Body__s

Trying that instead.

**Comment by AlainODea** [comment]
This issue is fixed. The renewed version works with the new Okta AWS app now.

I strongly recommend following the setup guide in the Okta Admin portal itself that is directly on the Amazon Web Services app you are configuring. It has changed significantly.

@mraible this can be closed 🎉
