### ISSUE TITLE
JNI error has occured

### ISSUE THREAD

**Issue by Russell-IO** [oktadeveloper/okta-aws-cli-assume-role#41]
Hello, I've followed the instructions in the readme, but I'm not able to log in.

{noformat}
⇒  ./awscli.command
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentials
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
{noformat}

**Comment by sepulworld** [comment]
Probably should  build everything in one jar...

https://github.com/oktadeveloper/okta-aws-cli-assume-role/pull/27 --- this PR plus my notes on the Jackson core stuff worked well.

**Comment by IamGabrielWu** [comment]
HI 
Please make sure your code work before it's on master. I followed okta [documentation](https://support.okta.com/help/Documentation/Knowledge_Article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta) here and it doesn't work leaving me really bad impression of using okta as a consumer.

**Comment by alamir1** [comment]
Latest update doesn't seem to work with Symantic VIP tokens. throws a runtime exception stating you don't have access to AWS.
also, if a token is generated the first time with another MFA method on one account or role, the second run fails if you try to generate a new token for another account or role while the first one hasn't expired. one must remove the session file and cache to generate a new token. very much broke the functonality in the old code

**Comment by AlainODea** [comment]
@alamir1 not sure why Symantec VIP doesn't work. I don't have a way to test that. Sorry about that.

#68 added a logout command that solves your other issue.

We have named profile support tested and ready to merge in #73 and multiple concurrent profile support is in development and a PR for that should be up early next week. After that we're working on being able to use the existing Okta session to switch profiles without having to re-authenticate.

**Comment by AlainODea** [comment]
@mraible this issue should be closed.

The original JNI crash is not reproducible and the rest of the comments here have strayed into random issue-reporting. All issues beyond the Symantec VIP issue are resolved and I've moved that to https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/74

**Comment by alamir1** [comment]
@AlainODea thanks for the update. I'll watch for the merge and try it again next week to try the Symantec VIP
