### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by jclerkin** [oktadeveloper/okta-aws-cli-assume-role#67]
After running './awscli sts get-caller-identity' and entering username and password, i then receive the following:

Exception in thread "main" java.net.UnknownHostException: https: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1504)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:843)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1494)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1353)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1287)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.okta.tools.OktaAwsCliAssumeRole.logInToOkta(OktaAwsCliAssumeRole.java:205)
	at com.okta.tools.OktaAwsCliAssumeRole.getAuthnResponse(OktaAwsCliAssumeRole.java:142)
	at com.okta.tools.OktaAwsCliAssumeRole.getOktaSessionToken(OktaAwsCliAssumeRole.java:125)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:86)
	at com.okta.tools.awscli.main(awscli.java:27)

**Comment by sergigp** [comment]
thank you for posting the solution @jclerkin

**Comment by AlainODea** [comment]
This is caused by setting OKTA_ORG to a URL instead of an FQDN. It tries to resolve https as a hostname in that case as it contricts a URL like https://{OKTA_ORG}/api/v1/authn.

**Comment by sergigp** [comment]
@AlainODea thx mate! solved! love u
