### ISSUE TITLE
Cannot setup and execute on Mac

### ISSUE THREAD

**Issue by ken5scal** [oktadeveloper/okta-aws-cli-assume-role#80]
I am using `MacBook Pro 10.12.6` and not being able to set up the cli correctly.
Here is the step by step setup.

1. Install JDK from  http://www.oracle.com/technetwork/java/javase/downloads/index.html

```
% java --version                                                                                    
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

2. % brew install maven
3. % git clone https://github.com/oktadeveloper/okta-aws-cli-assume-role.git
4. % vim config.properties (Edit OKTA_ORG and OKTA_AWS_APP_URL) 
5. % mv config.properties out
6. % mvn package
7. % cp target/okta-aws-cli-1.0-SNAPSHOT.jar out/oktaawscli.jar
8. % cd out

Now, I executed `./awscli sts get-caller-identity` and it gives me following error.

```
[ksuzuki@A-M-201711-003] ~/workspace/okta-aws-cli-assume-role/out
% ./awscli sts get-caller-identity                                                                              (git)-[master]
Username: ksuzuki (or ksuzuki@mydomain.com)
Password:
Exception in thread "main" java.net.UnknownHostException: https: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1504)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:843)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1494)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1353)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1287)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.okta.tools.OktaAwsCliAssumeRole.logInToOkta(OktaAwsCliAssumeRole.java:224)
	at com.okta.tools.OktaAwsCliAssumeRole.getAuthnResponse(OktaAwsCliAssumeRole.java:161)
	at com.okta.tools.OktaAwsCliAssumeRole.getOktaSessionToken(OktaAwsCliAssumeRole.java:144)
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:99)
	at com.okta.tools.awscli.main(awscli.java:29)
[ksuzuki@A-M-201711-003]
```

I am not sure what I am missing at this point. Any suggestion will be helpful.

**Comment by ken5scal** [comment]
Nevermind, I realized OKTA_ORG cannot  have scheme `https://`
