### ISSUE TITLE
CLI fails on Multiple Roles 

### ISSUE THREAD

**Issue by alamir1** [oktadeveloper/okta-aws-cli-assume-role#95]
first run works fine. But, if I run the commands again to get keys for a different role it fails unless I remove the session file ~/.okta-aws-cli-session
./awscli sts get-caller-identity
Exception in thread "main" java.lang.NullPointerException
at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:109)
at com.okta.tools.awscli.main(awscli.java:31)

**Comment by emalenfant-fuze** [comment]
I'll second the problem - same error:

```
awscli sts get-caller-identity
Exception in thread "main" java.lang.NullPointerException
	at com.okta.tools.OktaAwsCliAssumeRole.run(OktaAwsCliAssumeRole.java:109)
	at com.okta.tools.awscli.main(awscli.java:31)
```

**Comment by AlainODea** [comment]
Confirmed. I can reproduce the issue on **master**. Thank you for your report, @alamir1. Thank you for confirming, @emalenfant-fuze.

The fix is easy. This regression was accidentally introduced with the named profile support.

A quick fix is this:
```bash
export OKTA_PROFILE=“ “
```

I’ll get a real fix for this soon. Sorry 😊
